import {games} from './data/questions.js';import {extend} from './data/extended.js';import {load,save,level} from './storage.js';import {sfx,setSound,setMusic,ambient,stopAmbient} from './audio.js';import {GameEngine} from './gameEngine.js';import {FinalThroneCutscene} from './cinematics/finalThroneCutscene.js';extend(games);
import {secretMissions} from './data/secretQuestions.js';
import {InfiniteLoopMission} from './secret/infiniteLoop.js';
import {BlackMarketMission} from './secret/blackMarket.js?v=20260809-8';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],state=load(),keys=Object.keys(games);let chosen=null,current=null,qIndex=0,streak=0,hp=100,shield=60,scanReady=true,bossOpen=false,bossStep=0,echoTimers=[],echoMemoryActive=false,secretMode=false,secretScans=0,secretClock=null,secretDeadline=0,rewardGlitchTimer=null,loopRewardTimer=null,marketRewardTimer=null;
const engine=new GameEngine($('#world'),{hit:onHit,scan});
const finale=new FinalThroneCutscene($('#coronation3d'),{root:$('#coronation'),title:$('.cutscene-title'),skipButton:$('.cutscene-skip'),returnButton:$('.coronation-return')});
const infiniteLoop=new InfiniteLoopMission($('#infiniteLoop'),{onComplete:showInfiniteLoopRestored,onExit:returnFromInfiniteLoop});
const blackMarket=new BlackMarketMission($('#blackMarket'),{onComplete:showBlackMarketComplete,onExit:returnFromBlackMarket,sfx});
function launchFinale(){stopAmbient();screen('coronation');finale.play(state.selectedHero||'KAEL')}
function shuffled(items){const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result}
function setEchoReplay(visible,enabled=false){const button=$('.echo-replay');button.hidden=!visible;button.disabled=!enabled}
function clearEchoMemory(){echoTimers.forEach(clearTimeout);echoTimers=[];echoMemoryActive=false;const memory=$('#echoMemory');memory.hidden=true;memory.classList.remove('is-visible','signal-lost');setEchoReplay(false)}
function clearSecretClock(){clearInterval(secretClock);secretClock=null;$('#secretTimer').hidden=true}
function screen(id){if(id!=='game'){clearEchoMemory();clearSecretClock()}$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$('#modal').classList.add('hidden')}
function boot(){ambient('hub');$('.menu-continue').disabled=!state.selectedHero;screen('menu')}
function newGame(){chosen=null;Object.assign(state,{selectedHero:null,xp:0,recoveredCores:[],completedGames:[],secretUnlocked:[],secretCompleted:[],loot:[],gameCompleted:false,riftMaster:false,statistics:{correct:0,mistakes:0,bestStreak:0}});save(state);$$('.hunter').forEach(x=>x.classList.remove('selected'));$('#confirm').disabled=true;screen('story')}
function continueGame(){if(!state.selectedHero)return;screen('hub');renderHub()}
function returnToMissions(){engine.dispose();document.exitPointerLock?.();secretMode=false;current=null;stopAmbient();ambient('hub');screen('hub');renderHub()}
function renderHub(){const l=level(state.xp);$('#hub').classList.toggle('rift-master',!!state.riftMaster);$('#heroName').textContent=state.selectedHero;$('#level').textContent=l;$('#xp').textContent=state.xp;$('#heroAvatar').className='avatar '+state.selectedHero.toLowerCase();$('#coreCount').textContent=`${state.recoveredCores.length} / 3 CORES RECOVERED`;$$('[data-core]').forEach(x=>x.classList.toggle('on',state.recoveredCores.includes(x.dataset.core)));$('[data-action=sound]').textContent=state.soundEnabled?'SOUND ON':'SOUND OFF';$('#cards').innerHTML=keys.map((k,i)=>{const g=games[k],recovered=state.recoveredCores.includes(k),secret=state.secretUnlocked.includes(k)||state.completedGames.includes(k);return `<article class="card ${recovered?'recovered':''} ${secret?'secret-open':''}" style="--accent:${g.accent}"><div class="card-art" style="--art:url('assets/images/rift-panorama.png');--pos:${g.pos}"></div><div class="mission-index">0${i+1}</div><div class="mission-status">${recovered?'CORE SECURED':'RIFT OPEN'}</div><div class="card-info"><em>${g.location}</em><h2>${g.title}</h2><strong>${g.topic}</strong><p>${g.desc}</p><div class="core-emblem"><b>${g.core[0]}</b><span>${g.core} CORE</span></div><div class="actions"><button data-play="${k}">ENTER ZONE</button><button data-how="${k}">MISSION DATA</button>${secret?`<button class="hub-secret" data-secret="${k}">${k==='form'?(state.secretCompleted.includes(k)?'RE-ENTER THE INFINITE LOOP':'ENTER THE INFINITE LOOP'):(state.secretCompleted.includes(k)?'RE-ENTER SECRET RIFT':'ENTER SECRET RIFT')}</button>`:''}</div></div></article>`}).join('');$$('[data-play]').forEach(b=>b.onclick=()=>start(b.dataset.play));$$('[data-how]').forEach(b=>b.onclick=()=>how(b.dataset.how));$$('[data-secret]').forEach(b=>b.onclick=()=>startSecret(b.dataset.secret))}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}
function how(k){const g=games[k],bossRule=g.bossQuestions?`In the final battle, only ${g.boss} remains. Solve five new sentences and shoot the correct energy marker each time. Every correct hit removes 20% of its integrity; the fifth hit overloads the core.`:'During the boss phase, break its answer shield, then shoot the exposed boss.';modal(`<small>FIELD MANUAL // ${g.location}</small><h2>${g.title}</h2><p>${g.desc}</p><h3>COMBAT LOOP</h3><p>Read the transmission. Each answer is attached to a moving monster. Track the correct creature and click directly on the monster or its answer shield to shoot. Wrong hits damage your shield. ${bossRule}</p><h3>CONTROLS</h3><p><b>Mouse</b> Aim · <b>Left click</b> Shoot · <b>WASD</b> Move · <b>Space</b> Jump · <b>Shift</b> Dash · <b>Q</b> Grammar Scan · <b>ESC</b> Pause</p><button data-start="${k}">START MISSION</button>`);$('[data-start]').onclick=()=>start(k)}
function profile(){const loopRecord=state.secretCompleted.includes('form')?'<h3>CLASSIFIED RECORD</h3><p><b>THE INFINITE LOOP</b> — COMPLETED · <b>LOOPKEEPER</b> — DEFEATED · TITLE: <b>LOOPBREAKER</b></p>':'';modal(`<small>RIFT HUNTER DOSSIER</small><h2>${state.selectedHero} // LEVEL ${level(state.xp)}</h2><p>XP <b>${state.xp}</b> · CORES <b>${state.recoveredCores.length}/3</b> · COMPLETED <b>${state.completedGames.length}</b></p><p>CORRECT <b>${state.statistics.correct}</b> · MISTAKES <b>${state.statistics.mistakes}</b> · BEST STREAK <b>${state.statistics.bestStreak}</b></p>${loopRecord}<h3>RECOVERED LOOT</h3><p>${state.loot.length?state.loot.map(x=>`◈ ${x}`).join(' · '):'No artifacts recovered yet.'}</p><button data-change>CHANGE HUNTER</button>`);$('[data-change]').onclick=()=>{chosen=null;$('#confirm').disabled=true;screen('select')}}
function start(k){secretMode=false;clearEchoMemory();clearSecretClock();current=k;qIndex=0;streak=0;hp=100;shield=60;bossOpen=false;bossStep=0;scanReady=true;$('#bossBar').hidden=true;const musicButton=$('.combat-music');musicButton.textContent=state.musicEnabled?'MUSIC ON':'MUSIC OFF';musicButton.setAttribute('aria-pressed',String(state.musicEnabled));window.setMissionWeapon?.(k);stopAmbient();ambient(k);screen('game');$('#game').classList.remove('game-form','game-link','game-echo','secret-rift');$('#game').classList.add('game-'+k);const g=games[k],hero=state.selectedHero.toLowerCase();$('#hudAvatar').className='avatar '+hero;$('#hudName').textContent=state.selectedHero;$('#location').textContent=g.location;engine.init(keys.indexOf(k));next()}
function startSecret(k){if(!secretMissions[k]||!state.secretUnlocked.includes(k))return;clearTimeout(rewardGlitchTimer);$('#secretAlert').hidden=true;current=k;if(k==='form'){secretMode=false;$('#infiniteLoop').dataset.hero=(state.selectedHero||'KAEL').toLowerCase();stopAmbient();ambient('form');screen('infiniteLoop');infiniteLoop.play();return}if(k==='link'){secretMode=false;stopAmbient();ambient('link');screen('blackMarket');blackMarket.play(state.selectedHero||'KAEL');return}secretMode=true;clearEchoMemory();clearSecretClock();qIndex=0;bossStep=0;streak=0;hp=100;shield=40;secretScans=1;scanReady=true;bossOpen=false;$('#bossBar').hidden=true;const musicButton=$('.combat-music');musicButton.textContent=state.musicEnabled?'MUSIC ON':'MUSIC OFF';window.setMissionWeapon?.(k);stopAmbient();ambient(k);screen('game');$('#game').classList.remove('game-form','game-link','game-echo');$('#game').classList.add('game-'+k,'secret-rift');const data=secretMissions[k],hero=state.selectedHero.toLowerCase();$('#hudAvatar').className='avatar '+hero;$('#hudName').textContent=state.selectedHero;$('#location').textContent=data.location;engine.init(keys.indexOf(k));nextSecret()}
function showInfiniteLoopRestored(){infiniteLoop.clear();clearTimeout(loopRewardTimer);stopAmbient();screen('loopRestored');sfx.victory();loopRewardTimer=setTimeout(completeInfiniteLoop,6500)}
function completeInfiniteLoop(){clearTimeout(loopRewardTimer);const first=!state.secretCompleted.includes('form');infiniteLoop.clear();if(first)state.secretCompleted.push('form');state.xp+=first?400:120;if(!state.loot.includes('OMEGA KEY FRAGMENT I'))state.loot.push('OMEGA KEY FRAGMENT I');if(!state.loot.includes('TITLE: LOOPBREAKER'))state.loot.push('TITLE: LOOPBREAKER');save(state);sfx.victory();$('#secretReward').classList.add('key-reward');$('#secretReward').classList.remove('key-two');$('#secretRewardHeading').textContent='THE LOOP HAS ENDED';$('#secretRewardMission').textContent='THE INFINITE LOOP // BRIDGES RESTORED';$('#secretRewardItem').textContent='OMEGA KEY FRAGMENT // I';$('#secretRewardClass').textContent='SECRET LOOT KEY // 1 OF 3';$('#secretRewardTitle').hidden=false;$('#secretRewardTitle').innerHTML='NEW TITLE ACHIEVED <b>LOOPBREAKER</b>';$('#secretRewardText').textContent="One fragment recovered. Two hidden pieces still remain somewhere beyond LEXA's official map.";const hero=$('#secretRewardHero');hero.hidden=false;window.setSecretRewardHero?.(state.selectedHero.toLowerCase());const art=$('#secretRewardArt');art.hidden=false;art.src='assets/images/omega-key-fragment-1.png';stopAmbient();screen('secretReward')}
function returnFromInfiniteLoop(){infiniteLoop.clear();current=null;stopAmbient();ambient('hub');screen('hub');renderHub()}
function showBlackMarketComplete(){blackMarket.clear();clearTimeout(marketRewardTimer);stopAmbient();screen('marketComplete');sfx.victory();marketRewardTimer=setTimeout(completeBlackMarket,7000)}
function completeBlackMarket(){clearTimeout(marketRewardTimer);const first=!state.secretCompleted.includes('link');blackMarket.clear();if(first)state.secretCompleted.push('link');state.xp+=first?450:130;if(!state.loot.includes('OMEGA KEY FRAGMENT II'))state.loot.push('OMEGA KEY FRAGMENT II');if(!state.loot.includes('TITLE: DOUBLE AGENT'))state.loot.push('TITLE: DOUBLE AGENT');save(state);sfx.victory();const reward=$('#secretReward');reward.classList.add('key-reward','key-two');$('#secretRewardHeading').textContent='THE DOUBLE TRADE IS BROKEN';$('#secretRewardMission').textContent='THE BLACK MARKET // NETWORK DISMANTLED';$('#secretRewardItem').textContent='OMEGA KEY FRAGMENT // II';$('#secretRewardClass').textContent='SECRET LOOT KEY // 2 OF 3';const title=$('#secretRewardTitle');title.hidden=false;title.innerHTML='NEW TITLE ACHIEVED <b>DOUBLE AGENT</b>';$('#secretRewardText').textContent='The second fragment responds to the first. One final hidden piece remains beyond LEXA\'s official map.';const hero=$('#secretRewardHero');hero.hidden=false;window.setSecretRewardHero?.(state.selectedHero.toLowerCase());const art=$('#secretRewardArt');art.hidden=false;art.src='assets/images/omega-key-fragment-2.png';stopAmbient();screen('secretReward')}
function returnFromBlackMarket(){blackMarket.clear();current=null;stopAmbient();ambient('hub');screen('hub');renderHub()}
function setBossHealth(value){const bar=$('#bossBar'),safe=Math.max(0,value);bar.hidden=false;bar.querySelector('i').style.width=safe+'%';bar.querySelector('span').textContent=safe+'%';bar.classList.toggle('critical',safe<=40)}
function startSecretClock(q){clearSecretClock();const timer=$('#secretTimer');timer.hidden=false;secretDeadline=performance.now()+9000;const tick=()=>{const left=Math.max(0,secretDeadline-performance.now());timer.querySelector('b').textContent=(left/1000).toFixed(1);timer.classList.toggle('critical',left<3000);if(left<=0){clearSecretClock();engine.clearTargets();$('#lexa').textContent='LEXA // RIFT WINDOW MISSED. The anomaly strikes back!';damagePlayer(q);if(hp>0)setTimeout(nextSecret,500)}};tick();secretClock=setInterval(tick,80)}
function nextSecret(){if(!secretMode)return;const data=secretMissions[current],boss=qIndex>=data.questions.length,q=boss?data.bossQuestions[bossStep]:data.questions[qIndex];if(!q)return;if(boss){const phase=Math.floor(bossStep/2)+1;$('#bossBarName').textContent=`${data.boss} // PHASE ${phase} / 3`;$('#question').textContent=q[0];$('#progress').textContent=`OMEGA PHASE ${phase} // ${bossStep+1} / ${data.bossQuestions.length}`;$('#lexa').textContent=`LEXA // OMEGA GLITCH phase ${phase}. One Grammar Scan remains for the entire rift.`;setBossHealth(100-bossStep/data.bossQuestions.length*100);if(bossStep)engine.updateSoloBoss(shuffled(q[1]));else engine.spawnSoloBoss(shuffled(q[1]),data.bossArt)}else{$('#question').textContent=q[0];$('#progress').textContent=`SECRET ${qIndex+1} / ${data.questions.length}`;$('#lexa').textContent=`LEXA // CLASSIFIED TEST. ${secretScans} Grammar Scan remaining.`;engine.spawn(shuffled(q[1]),false)}updateHud();startSecretClock(q)}
function secretHit(data,obj){const mission=secretMissions[current],boss=qIndex>=mission.questions.length,q=boss?mission.bossQuestions[bossStep]:mission.questions[qIndex],ok=data.answer===q[2];engine.flash(obj,ok);if(!ok){damagePlayer(q);return}clearSecretClock();rewardCorrect();if(!boss){qIndex++;setTimeout(nextSecret,300);return}bossStep++;engine.damageSoloBoss();setBossHealth(100-bossStep/mission.bossQuestions.length*100);if(bossStep===mission.bossQuestions.length){$('#question').textContent='OMEGA CORE COLLAPSE';$('#progress').textContent='SECRET MISSION COMPLETE';$('#lexa').textContent='LEXA // The classified anomaly has been erased.';engine.explodeSoloBoss(()=>setTimeout(secretVictory,300));return}if(bossStep%2===0)$('#lexa').textContent=`LEXA // PHASE ${bossStep/2} DESTROYED. OMEGA is mutating!`;setTimeout(nextSecret,500)}
function secretVictory(){const data=secretMissions[current],first=!state.secretCompleted.includes(current);clearSecretClock();engine.dispose();document.exitPointerLock?.();state.xp+=first?300:100;if(first)state.secretCompleted.push(current);if(!state.loot.includes(data.reward))state.loot.push(data.reward);save(state);sfx.victory();$('#secretReward').classList.remove('key-reward','key-two');$('#secretRewardHeading').textContent='SECRET RIFT SEALED';$('#secretRewardMission').textContent=data.title;$('#secretRewardItem').textContent=data.reward;$('#secretRewardClass').textContent=data.rewardClass;$('#secretRewardTitle').hidden=true;$('#secretRewardText').textContent='This artifact exists nowhere else on Lexara-9. LEXA has erased the route back to the experimental sector.';$('#secretRewardHero').hidden=true;$('#secretRewardArt').hidden=true;stopAmbient();screen('secretReward')}
function showEchoMemory(q){clearEchoMemory();echoMemoryActive=true;setEchoReplay(true,false);engine.clearTargets();const memory=$('#echoMemory'),meta=q[4]||{};$('#echoSpeaker').textContent=meta.speaker||'UNKNOWN SIGNAL';$('#echoQuote').textContent=`“${meta.quote||''}”`;memory.hidden=false;memory.classList.add('is-visible');$('#question').textContent=`MEMORY MODE // ${meta.mode==='question'?'QUESTION':meta.mode==='command'?'COMMAND':'MESSAGE'}`;$('#progress').textContent=`${qIndex} / 8`;$('#lexa').textContent='LEXA // Memorize the transmission. Enemies will appear when the signal is lost.';updateHud();echoTimers.push(setTimeout(()=>{memory.classList.add('signal-lost');$('#question').textContent=q[0];$('#lexa').textContent='LEXA // SIGNAL LOST. Restore the original transmission.'},3400));echoTimers.push(setTimeout(()=>{echoMemoryActive=false;memory.hidden=true;memory.classList.remove('is-visible','signal-lost');setEchoReplay(true,true);engine.spawn(shuffled(q[1]),false)},4300))}
function replayEchoMemory(){if(current!=='echo'||qIndex>=7||echoMemoryActive)return;const q=games.echo.questions[qIndex%games.echo.questions.length],meta=q[4];if(!meta)return;clearEchoMemory();echoMemoryActive=true;setEchoReplay(true,false);const memory=$('#echoMemory');$('#echoSpeaker').textContent=meta.speaker||'UNKNOWN SIGNAL';$('#echoQuote').textContent=`“${meta.quote||''}”`;memory.hidden=false;memory.classList.add('is-visible');$('#lexa').textContent='LEXA // Transmission replay active. Memorize the original words.';echoTimers.push(setTimeout(()=>{echoMemoryActive=false;memory.hidden=true;memory.classList.remove('is-visible');setEchoReplay(true,true);$('#lexa').textContent='LEXA // Replay ended. Fire at the correct restored message.'},3200))}
function next(){if(secretMode){nextSecret();return}const g=games[current];if(g.bossQuestions&&qIndex===7){clearEchoMemory();const q=g.bossQuestions[bossStep];$('#bossBarName').textContent=`${g.boss} // INTEGRITY`;$('#question').textContent=`BOSS // ${q[0]}`;$('#progress').textContent=`BOSS ${bossStep+1} / ${g.bossQuestions.length}`;$('#lexa').textContent=bossStep?'LEXA // Core damaged. Lock the next correct answer!':`LEXA // ${g.boss} detected. Five correct shots will overload its core!`;setBossHealth(100-bossStep*20);if(bossStep)engine.updateSoloBoss(shuffled(q[1]));else engine.spawnSoloBoss(shuffled(q[1]),g.bossArt);updateHud();return}const q=g.questions[qIndex%g.questions.length],isBoss=qIndex===7;if(current==='echo'&&q[4]){showEchoMemory(q);return}$('#question').textContent=isBoss?`BOSS SHIELD // ${q[0]}`:q[0];$('#progress').textContent=`${qIndex} / 8`;$('#lexa').textContent=isBoss?`LEXA // ${g.boss} detected. Break the answer shield!`:'LEXA // Fire at the creature carrying the correct answer.';engine.spawn(shuffled(q[1]),isBoss);updateHud()}
function rewardCorrect(){sfx.correct();streak++;state.statistics.correct++;state.xp+=scanReady?20:10;state.statistics.bestStreak=Math.max(state.statistics.bestStreak,streak);if(streak%5===0)state.xp+=30;save(state);updateHud()}
function damagePlayer(q){sfx.wrong();streak=0;state.statistics.mistakes++;if(shield>0)shield=Math.max(0,shield-20);else hp=Math.max(0,hp-25);document.body.classList.add('hit');setTimeout(()=>document.body.classList.remove('hit'),220);$('#lexa').textContent=`LEXA // ERROR. ${q[3]}`;save(state);updateHud();if(!hp)gameOver()}
function onHit(data,obj){if(echoMemoryActive)return;if(secretMode){secretHit(data,obj);return}const g=games[current];if(g.bossQuestions&&qIndex===7){const q=g.bossQuestions[bossStep],ok=data.answer===q[2];engine.flash(obj,ok);if(!ok){damagePlayer(q);return}rewardCorrect();bossStep++;engine.damageSoloBoss();setBossHealth(100-bossStep*20);if(bossStep===g.bossQuestions.length){$('#question').textContent='CORE OVERLOAD // CRITICAL HIT';$('#progress').textContent='BOSS DEFEATED';$('#lexa').textContent=`LEXA // ${g.core} CORE released. ${g.boss} is collapsing!`;$('#bossBar').classList.add('destroyed');engine.explodeSoloBoss(()=>{setTimeout(victory,300)});return}setTimeout(next,430);return}const q=g.questions[qIndex%g.questions.length];if(bossOpen){sfx.hit();engine.flash(obj,true);victory();return}const ok=data.answer===q[2];engine.flash(obj,ok);if(ok){setEchoReplay(false);rewardCorrect();if(qIndex===7){bossOpen=true;$('#question').textContent='SHIELD DOWN // FIRE AT THE BOSS';$('#lexa').textContent='LEXA // Damage phase! Shoot the exposed core!';engine.targets.forEach(x=>x.userData.answer=q[2]);return}qIndex++;setTimeout(next,360)}else damagePlayer(q)}
function updateHud(){const l=level(state.xp);$('#health').value=hp;$('#shield').value=shield;$('#hudXp').textContent=state.xp;$('#hudLevel').textContent=l;$('#streak').textContent=streak}
function scan(){if(!current||!scanReady||echoMemoryActive)return;if(secretMode){if(!secretScans){$('#lexa').textContent='LEXA // GRAMMAR SCAN DEPLETED IN THIS SECRET RIFT.';return}const data=secretMissions[current],q=qIndex>=data.questions.length?data.bossQuestions[bossStep]:data.questions[qIndex];secretScans--;scanReady=false;$('#lexa').textContent='LIMITED GRAMMAR SCAN // '+q[3];return}scanReady=false;const g=games[current],q=g.bossQuestions&&qIndex===7?g.bossQuestions[bossStep]:g.questions[qIndex%g.questions.length];$('#lexa').textContent='GRAMMAR SCAN // '+q[3];$('#scan').textContent='SCAN RECHARGING // 10';let n=10;const t=setInterval(()=>{n--;$('#scan').textContent=`SCAN RECHARGING // ${n}`;if(!n){clearInterval(t);scanReady=true;$('#scan').textContent='[Q] GRAMMAR SCAN READY'}},1000)}
const loot=['Scrap Visor','Syntax Scope','Echo Jacket','Particle Backpack','Rift Helmet','Neon Guard','Form Breaker','Core Hunter Armor','Void Glasses','Glitch Boots','Grammar Reactor','Lexa Crown'];
function showCoreReward(mission){const hero=state.selectedHero.toLowerCase(),reward=$('#formReward'),copy={form:{mission:'MISSION 01 COMPLETE',matrix:'FORM MATRIX RESTORED',type:'NEW WEAPON ACQUIRED',item:'RIFTBREAKER',itemClass:'FORM-CORE SHOTGUN // LEGENDARY',boss:'THE REGRETTER HAS FALLEN.',story:"LEXA's FORM matrix is online — but Lexara-9 is still breaking apart.",next:'<b>Two cores remain.</b> Enter Neon Scrap City, defeat Lord Particle and recover the LINK CORE.',nextCore:'LINK CORE',nextZone:'NEON SCRAP CITY',status:'FORM SECURED',art:'riftbreaker-shotgun-source.png'},link:{mission:'MISSION 02 COMPLETE',matrix:'LINK MATRIX RESTORED',type:'NEW DEFENCE ACQUIRED',item:'PARTICLE AEGIS',itemClass:'LINK-CORE ENERGY SHIELD // LEGENDARY',boss:'LORD PARTICLE HAS FALLEN.',story:"LEXA's LINK matrix is online — Neon Scrap City can understand commands again.",next:'<b>One core remains.</b> Enter the Echo Station, defeat The Distorter and recover the ECHO CORE.',nextCore:'ECHO CORE',nextZone:'THE ECHO STATION',status:'FORM + LINK SECURED',art:'particle-aegis-source.png'},echo:{mission:'FINAL MISSION COMPLETE',matrix:'LEXA SYSTEM RESTORED',type:'ULTIMATE ARTIFACT ACQUIRED',item:'LEXA CROWN',itemClass:'THREE-CORE CROWN // MYTHIC',boss:'THE DISTORTER HAS BEEN ERASED.',story:'FORM, LINK and ECHO are synchronized. LEXA is whole again and every system on Lexara-9 is coming back online.',next:'<b>Lexara-9 is saved.</b> The language rifts are sealed. Your name is now recorded among the legendary Rift Hunters.',nextCore:'SYSTEM ONLINE',nextZone:'LEXARA-9 RESTORED',status:'ALL 3 CORES SECURED',art:'lexa-crown-source.png'}}[mission];reward.className='screen reward-'+mission;$('#secretAlert').hidden=true;reward.classList.remove('secret-interrupt');$('#rewardHero').src=`assets/images/${hero}-reward.png`;$('#rewardHero').className='reward-hero '+hero;$('#rewardMission').textContent=copy.mission;$('#rewardMatrix').textContent=copy.matrix;$('#rewardType').textContent=copy.type;$('#rewardItemName').textContent=copy.item;$('#rewardItemClass').textContent=copy.itemClass;$('#rewardBossText').textContent=copy.boss;$('#rewardStory').textContent=copy.story;$('#rewardNext').innerHTML=copy.next;$('#rewardNextCore').textContent=copy.nextCore;$('#rewardNextZone').textContent=copy.nextZone;$('#rewardCoreStatus').textContent=copy.status;$('#rewardHeroName').textContent=state.selectedHero;$('#rewardLevel').textContent=level(state.xp);$('#rewardXp').textContent=state.xp;$('#rewardCores').textContent=state.recoveredCores.length;window.setRewardItem?.(copy.art);stopAmbient();screen('formReward');clearTimeout(rewardGlitchTimer);const secretDelay=mission==='echo'?12000:9500;rewardGlitchTimer=setTimeout(()=>{if(!reward.classList.contains('active'))return;reward.classList.add('secret-interrupt');$('#secretAlert').hidden=false;sfx.wrong()},secretDelay)}
function victory(){const g=games[current];$('#bossBar').hidden=true;$('#bossBar').classList.remove('critical','destroyed');engine.dispose();document.exitPointerLock?.();state.xp+=150;if(!state.recoveredCores.includes(current))state.recoveredCores.push(current);if(!state.completedGames.includes(current))state.completedGames.push(current);if(!state.secretUnlocked.includes(current))state.secretUnlocked.push(current);const item=current==='form'?'Riftbreaker Shotgun':current==='link'?'Particle Aegis Shield':current==='echo'?'Lexa Crown':loot[Math.floor(Math.random()*loot.length)];if(!state.loot.includes(item))state.loot.push(item);save(state);sfx.victory();if(g.bossQuestions){showCoreReward(current);return}modal(`<small>MISSION COMPLETE</small><h2>${g.core} CORE RECOVERED</h2><p>${g.boss} has been erased from the rift.</p><h3>LOOT DROP // ${item}</h3><p>+150 XP · Core synchronized with LEXA.</p><button data-hub>RETURN TO HUB</button>`);$('[data-hub]').onclick=()=>{current=null;stopAmbient();ambient('hub');screen('hub');renderHub()}}
function gameOver(){const wasSecret=secretMode,mission=current;clearSecretClock();engine.dispose();document.exitPointerLock?.();modal(`<small>CONNECTION LOST</small><h2>${wasSecret?'OMEGA GLITCH CONSUMED THE SIGNAL':'YOU WERE GLITCHED'}</h2><p>The rift remains unstable. Recalibrate and try again.</p><button data-retry>RETRY MISSION</button> <button data-hub>RETURN TO HUB</button>`);$('[data-retry]').onclick=()=>wasSecret?startSecret(mission):start(mission);$('[data-hub]').onclick=()=>{secretMode=false;current=null;screen('hub');renderHub()}}
document.addEventListener('pointerlockchange',()=>{if(!$('#game').classList.contains('active'))return;if(current&&document.pointerLockElement!==$('#world')&&!$('#modal').classList.contains('hidden'))return;if(current&&document.pointerLockElement!==$('#world')){if(secretMode)clearSecretClock();modal(`<small>MISSION PAUSED</small><h2>RIFT LINK SUSPENDED</h2><button data-resume>RETURN TO GAME</button> <button data-hub>RETURN TO HUB</button>`);$('[data-resume]').onclick=()=>{$('#modal').classList.add('hidden');$('#world').requestPointerLock();if(secretMode)nextSecret()};$('[data-hub]').onclick=()=>{clearSecretClock();engine.dispose();secretMode=false;current=null;screen('hub');renderHub()}}});
document.addEventListener('mouseover',e=>{if(e.target.closest('button'))sfx.hover()});document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;sfx.click();const a=b.dataset.action;if(a==='boot')boot();if(a==='close')$('#modal').classList.add('hidden');if(a==='profile')profile();if(a==='sound'){state.soundEnabled=!state.soundEnabled;setSound(state.soundEnabled);save(state);renderHub()}if(a==='music'){state.musicEnabled=!state.musicEnabled;setMusic(state.musicEnabled);stopAmbient();if(state.musicEnabled)ambient(current||'hub');b.textContent=state.musicEnabled?'MUSIC ON':'MUSIC OFF';b.setAttribute('aria-pressed',String(state.musicEnabled));save(state)}if(a==='echo-replay')replayEchoMemory();if(a==='enter-secret'){clearTimeout(rewardGlitchTimer);startSecret(current)}if(a==='loop-exit')infiniteLoop.exit();if(a==='loop-reward'){clearTimeout(loopRewardTimer);completeInfiniteLoop()}if(a==='secret-return'){secretMode=false;if(current==='echo'&&!state.gameCompleted){launchFinale();return}current=null;ambient('hub');screen('hub');renderHub()}if(a==='reset'&&confirm('Reset all LEXA:RIFT progress?')){localStorage.removeItem('lexaRift');location.reload()}if(a==='confirm'&&chosen){state.selectedHero=chosen;save(state);screen('hub');renderHub()}});
$('#story .story-continue').onclick=()=>{chosen=null;$$('.hunter').forEach(x=>x.classList.remove('selected'));$('#confirm').disabled=true;screen('select')};
$('.menu-new').onclick=newGame;
$('.menu-continue').onclick=continueGame;
$('.return-missions').onclick=returnToMissions;
$('.reward-return').onclick=()=>{clearTimeout(rewardGlitchTimer);$('#secretAlert').hidden=true;if(current==='echo'){launchFinale();return}current=null;ambient('hub');screen('hub');renderHub()};
$('[data-action="market-reward"]').onclick=()=>completeBlackMarket();
$('.cutscene-skip').onclick=()=>finale.skip();
$('.coronation-return').onclick=()=>{finale.dispose();state.gameCompleted=true;state.riftMaster=true;if(!state.loot.includes('LEXA CROWN // LEGENDARY'))state.loot.push('LEXA CROWN // LEGENDARY');save(state);current=null;ambient('hub');screen('hub');renderHub()};
$$('.hunter').forEach(b=>b.onclick=()=>{chosen=b.dataset.hero;$$('.hunter').forEach(x=>x.classList.toggle('selected',x===b));$('#confirm').disabled=false});setSound(state.soundEnabled);setMusic(state.musicEnabled);const preview=new URLSearchParams(location.search).get('preview');if(games[preview]){state.selectedHero||='KAEL';start(preview)}
