import {games} from './data/questions.js';import {extend} from './data/extended.js';import {load,save,level} from './storage.js';import {sfx,setSound,ambient,stopAmbient} from './audio.js';import {GameEngine} from './gameEngine.js';extend(games);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],state=load(),keys=Object.keys(games);let chosen=null,current=null,qIndex=0,streak=0,hp=100,shield=60,scanReady=true,bossOpen=false;
const engine=new GameEngine($('#world'),{hit:onHit,scan});
function shuffled(items){const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result}
function screen(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$('#modal').classList.add('hidden')}
function boot(){ambient('hub');$('.menu-continue').disabled=!state.selectedHero;screen('menu')}
function newGame(){chosen=null;Object.assign(state,{selectedHero:null,xp:0,recoveredCores:[],completedGames:[],loot:[],statistics:{correct:0,mistakes:0,bestStreak:0}});save(state);$$('.hunter').forEach(x=>x.classList.remove('selected'));$('#confirm').disabled=true;screen('story')}
function continueGame(){if(!state.selectedHero)return;screen('hub');renderHub()}
function returnToMissions(){engine.dispose();document.exitPointerLock?.();current=null;stopAmbient();ambient('hub');screen('hub');renderHub()}
function renderHub(){const l=level(state.xp);$('#heroName').textContent=state.selectedHero;$('#level').textContent=l;$('#xp').textContent=state.xp;$('#heroAvatar').className='avatar '+state.selectedHero.toLowerCase();$('#coreCount').textContent=`${state.recoveredCores.length} / 3 CORES RECOVERED`;$$('[data-core]').forEach(x=>x.classList.toggle('on',state.recoveredCores.includes(x.dataset.core)));$('[data-action=sound]').textContent=state.soundEnabled?'SOUND ON':'SOUND OFF';$('#cards').innerHTML=keys.map((k,i)=>{const g=games[k],recovered=state.recoveredCores.includes(k);return `<article class="card ${recovered?'recovered':''}" style="--accent:${g.accent}"><div class="card-art" style="--art:url('assets/images/rift-panorama.png');--pos:${g.pos}"></div><div class="mission-index">0${i+1}</div><div class="mission-status">${recovered?'CORE SECURED':'RIFT OPEN'}</div><div class="card-info"><em>${g.location}</em><h2>${g.title}</h2><strong>${g.topic}</strong><p>${g.desc}</p><div class="core-emblem"><b>${g.core[0]}</b><span>${g.core} CORE</span></div><div class="actions"><button data-play="${k}">ENTER ZONE</button><button data-how="${k}">MISSION DATA</button></div></div></article>`}).join('');$$('[data-play]').forEach(b=>b.onclick=()=>start(b.dataset.play));$$('[data-how]').forEach(b=>b.onclick=()=>how(b.dataset.how))}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}
function how(k){const g=games[k];modal(`<small>FIELD MANUAL // ${g.location}</small><h2>${g.title}</h2><p>${g.desc}</p><h3>COMBAT LOOP</h3><p>Read the transmission. Each answer is attached to a moving monster. Track the correct creature and click directly on the monster or its answer shield to shoot. Wrong hits damage your shield. During the boss phase, break its answer shield, then shoot the exposed boss.</p><h3>CONTROLS</h3><p><b>Mouse</b> Aim · <b>Left click</b> Shoot · <b>WASD</b> Move · <b>Space</b> Jump · <b>Shift</b> Dash · <b>Q</b> Grammar Scan · <b>ESC</b> Pause</p><button data-start="${k}">START MISSION</button>`);$('[data-start]').onclick=()=>start(k)}
function profile(){modal(`<small>RIFT HUNTER DOSSIER</small><h2>${state.selectedHero} // LEVEL ${level(state.xp)}</h2><p>XP <b>${state.xp}</b> · CORES <b>${state.recoveredCores.length}/3</b> · COMPLETED <b>${state.completedGames.length}</b></p><p>CORRECT <b>${state.statistics.correct}</b> · MISTAKES <b>${state.statistics.mistakes}</b> · BEST STREAK <b>${state.statistics.bestStreak}</b></p><h3>RECOVERED LOOT</h3><p>${state.loot.length?state.loot.map(x=>`◈ ${x}`).join(' · '):'No artifacts recovered yet.'}</p><button data-change>CHANGE HUNTER</button>`);$('[data-change]').onclick=()=>{chosen=null;$('#confirm').disabled=true;screen('select')}}
function start(k){current=k;qIndex=0;streak=0;hp=100;shield=60;bossOpen=false;stopAmbient();ambient(k);screen('game');$('#game').classList.remove('game-form','game-link','game-echo');$('#game').classList.add('game-'+k);const g=games[k],hero=state.selectedHero.toLowerCase();$('#hudAvatar').className='avatar '+hero;$('#hudName').textContent=state.selectedHero;$('#location').textContent=g.location;engine.init(keys.indexOf(k));next()}
function next(){const g=games[current],q=g.questions[qIndex%g.questions.length],isBoss=qIndex===7;$('#question').textContent=isBoss?`BOSS SHIELD // ${q[0]}`:q[0];$('#progress').textContent=`${qIndex} / 8`;$('#lexa').textContent=isBoss?`LEXA // ${g.boss} detected. Break the answer shield!`:'LEXA // Fire at the creature carrying the correct form.';engine.spawn(shuffled(q[1]),isBoss);updateHud()}
function onHit(data,obj){const q=games[current].questions[qIndex%games[current].questions.length];if(bossOpen){sfx.hit();engine.flash(obj,true);victory();return}const ok=data.answer===q[2];engine.flash(obj,ok);if(ok){sfx.correct();streak++;state.statistics.correct++;state.xp+=scanReady?20:10;state.statistics.bestStreak=Math.max(state.statistics.bestStreak,streak);if(streak%5===0)state.xp+=30;if(qIndex===7){bossOpen=true;$('#question').textContent='SHIELD DOWN // FIRE AT THE BOSS';$('#lexa').textContent='LEXA // Damage phase! Shoot the exposed core!';engine.targets.forEach(x=>x.userData.answer=q[2]);return}qIndex++;save(state);setTimeout(next,360)}else{sfx.wrong();streak=0;state.statistics.mistakes++;if(shield>0)shield=Math.max(0,shield-20);else hp=Math.max(0,hp-25);document.body.classList.add('hit');setTimeout(()=>document.body.classList.remove('hit'),220);$('#lexa').textContent=`LEXA // ERROR. ${q[3]}`;save(state);updateHud();if(!hp)gameOver()}}
function updateHud(){const l=level(state.xp);$('#health').value=hp;$('#shield').value=shield;$('#hudXp').textContent=state.xp;$('#hudLevel').textContent=l;$('#streak').textContent=streak}
function scan(){if(!current||!scanReady)return;scanReady=false;const q=games[current].questions[qIndex%games[current].questions.length];$('#lexa').textContent='GRAMMAR SCAN // '+q[3];$('#scan').textContent='SCAN RECHARGING // 10';let n=10;const t=setInterval(()=>{n--;$('#scan').textContent=`SCAN RECHARGING // ${n}`;if(!n){clearInterval(t);scanReady=true;$('#scan').textContent='[Q] GRAMMAR SCAN READY'}},1000)}
const loot=['Scrap Visor','Syntax Scope','Echo Jacket','Particle Backpack','Rift Helmet','Neon Guard','Form Breaker','Core Hunter Armor','Void Glasses','Glitch Boots','Grammar Reactor','Lexa Crown'];
function victory(){const g=games[current];engine.dispose();document.exitPointerLock?.();state.xp+=150;if(!state.recoveredCores.includes(current))state.recoveredCores.push(current);if(!state.completedGames.includes(current))state.completedGames.push(current);const item=loot[Math.floor(Math.random()*loot.length)];if(!state.loot.includes(item))state.loot.push(item);save(state);sfx.victory();modal(`<small>MISSION COMPLETE</small><h2>${g.core} CORE RECOVERED</h2><p>${g.boss} has been erased from the rift.</p><h3>LOOT DROP // ${item}</h3><p>+150 XP · Core synchronized with LEXA.</p><button data-hub>RETURN TO HUB</button>`);$('[data-hub]').onclick=()=>{current=null;stopAmbient();ambient('hub');screen('hub');renderHub()}}
function gameOver(){engine.dispose();document.exitPointerLock?.();modal(`<small>CONNECTION LOST</small><h2>YOU WERE GLITCHED</h2><p>The rift remains unstable. Recalibrate and try again.</p><button data-retry>RETRY MISSION</button> <button data-hub>RETURN TO HUB</button>`);$('[data-retry]').onclick=()=>start(current);$('[data-hub]').onclick=()=>{current=null;screen('hub');renderHub()}}
document.addEventListener('pointerlockchange',()=>{if(current&&document.pointerLockElement!==$('#world')&&!$('#modal').classList.contains('hidden'))return;if(current&&document.pointerLockElement!==$('#world'))modal(`<small>MISSION PAUSED</small><h2>RIFT LINK SUSPENDED</h2><button data-resume>RETURN TO GAME</button> <button data-hub>RETURN TO HUB</button>`),$('[data-resume]').onclick=()=>{$('#modal').classList.add('hidden');$('#world').requestPointerLock()},$('[data-hub]').onclick=()=>{engine.dispose();current=null;screen('hub');renderHub()}});
document.addEventListener('mouseover',e=>{if(e.target.closest('button'))sfx.hover()});document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;sfx.click();const a=b.dataset.action;if(a==='boot')boot();if(a==='close')$('#modal').classList.add('hidden');if(a==='profile')profile();if(a==='sound'){state.soundEnabled=!state.soundEnabled;setSound(state.soundEnabled);save(state);renderHub()}if(a==='reset'&&confirm('Reset all LEXA:RIFT progress?')){localStorage.removeItem('lexaRift');location.reload()}if(a==='confirm'&&chosen){state.selectedHero=chosen;save(state);screen('hub');renderHub()}});
$('#story .story-continue').onclick=()=>{chosen=null;$$('.hunter').forEach(x=>x.classList.remove('selected'));$('#confirm').disabled=true;screen('select')};
$('.menu-new').onclick=newGame;
$('.menu-continue').onclick=continueGame;
$('.return-missions').onclick=returnToMissions;
$$('.hunter').forEach(b=>b.onclick=()=>{chosen=b.dataset.hero;$$('.hunter').forEach(x=>x.classList.toggle('selected',x===b));$('#confirm').disabled=false});setSound(state.soundEnabled);const preview=new URLSearchParams(location.search).get('preview');if(games[preview]){state.selectedHero||='KAEL';start(preview)}
