let ctx,enabled=true,musicEnabled=true,hum,musicTimer,musicBus,musicStep=0,nextBeat=0,currentMode='hub';
export function setSound(v){enabled=v;if(ctx){ctx.resume();if(musicBus)musicBus.gain.setTargetAtTime(v ? .15 : 0,ctx.currentTime,.08)}}
export function setMusic(v){musicEnabled=v;if(ctx&&musicBus)musicBus.gain.setTargetAtTime(enabled&&v ? .15 : 0,ctx.currentTime,.08)}
function tone(f=220,d=.08,type='square',vol=.035){if(!enabled)return;ctx??=new AudioContext();const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(vol,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+d);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+d)}
export const sfx={hover:()=>tone(420,.03),click:()=>tone(250,.06),shot:()=>tone(100,.08,'sawtooth',.06),electric:()=>{tone(88,.13,'sawtooth',.075);setTimeout(()=>tone(1380,.08,'square',.045),18);setTimeout(()=>tone(720,.11,'sawtooth',.04),48)},flame:()=>{tone(58,.3,'sawtooth',.075);setTimeout(()=>tone(92,.24,'triangle',.045),25);setTimeout(()=>tone(42,.32,'square',.03),55)},correct:()=>{tone(660,.12);setTimeout(()=>tone(990,.18),80)},wrong:()=>tone(75,.3,'sawtooth',.08),hit:()=>tone(180,.05),death:()=>tone(55,.5,'square',.07),xp:()=>tone(850,.1),level:()=>tone(1200,.5,'sine',.08),victory:()=>[440,660,880].forEach((x,i)=>setTimeout(()=>tone(x,.35,'triangle',.06),i*120))};
const musicModes={
  hub:{bpm:76,root:46.25,scale:[0,3,5,7,10],bass:[0,0,3,0,5,3,0,-2],lead:[7,10,12,10,7,5,3,5]},
  form:{bpm:94,root:55,scale:[0,3,5,7,10],bass:[0,0,-2,0,3,0,5,3],lead:[12,10,7,5,7,10,5,3]},
  link:{bpm:108,root:61.74,scale:[0,2,5,7,9],bass:[0,-3,0,2,5,2,0,-3],lead:[12,9,7,5,9,12,14,9]},
  echo:{bpm:88,root:41.2,scale:[0,1,5,7,8],bass:[0,0,1,0,-4,1,0,-2],lead:[12,8,7,5,8,7,1,5]}
};
function note(root,semitones){return root*Math.pow(2,semitones/12)}
function envNode(time,duration,volume){const g=ctx.createGain();g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(volume,time+.012);g.gain.exponentialRampToValueAtTime(.0001,time+duration);g.connect(musicBus);return g}
function bassHit(time,freq,accent=1){const o=ctx.createOscillator(),f=ctx.createBiquadFilter(),g=envNode(time,.34,.12*accent);o.type='sawtooth';o.frequency.setValueAtTime(freq,time);o.frequency.exponentialRampToValueAtTime(freq*.985,time+.3);f.type='lowpass';f.frequency.value=260;f.Q.value=3;o.connect(f).connect(g);o.start(time);o.stop(time+.36)}
function metalHit(time,accent=1){const length=Math.floor(ctx.sampleRate*.09),buffer=ctx.createBuffer(1,length,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/length,2);const src=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),g=envNode(time,.1,.055*accent);src.buffer=buffer;filter.type='highpass';filter.frequency.value=accent>1?2800:1400;src.connect(filter).connect(g);src.start(time)}
function kick(time,accent=1){const o=ctx.createOscillator(),g=envNode(time,.16,.11*accent);o.type='sine';o.frequency.setValueAtTime(105,time);o.frequency.exponentialRampToValueAtTime(42,time+.14);o.connect(g);o.start(time);o.stop(time+.17)}
function twang(time,freq){const o=ctx.createOscillator(),o2=ctx.createOscillator(),f=ctx.createBiquadFilter(),g=envNode(time,.42,.032);o.type='triangle';o2.type='square';o.frequency.value=freq;o2.frequency.value=freq*2.003;f.type='bandpass';f.frequency.value=freq*2.2;f.Q.value=5;o.connect(f);o2.connect(f);f.connect(g);o.start(time);o2.start(time);o.stop(time+.44);o2.stop(time+.44)}
function neonPulse(time,freq,accent=1){const o=ctx.createOscillator(),g=envNode(time,.16,.038*accent),f=ctx.createBiquadFilter();o.type='square';o.frequency.setValueAtTime(freq,time);f.type='lowpass';f.frequency.setValueAtTime(1800,time);f.frequency.exponentialRampToValueAtTime(380,time+.15);o.connect(f).connect(g);o.start(time);o.stop(time+.17)}
function darkTom(time,freq=72){const o=ctx.createOscillator(),g=envNode(time,.42,.07);o.type='sine';o.frequency.setValueAtTime(freq,time);o.frequency.exponentialRampToValueAtTime(freq*.55,time+.38);o.connect(g);o.start(time);o.stop(time+.44)}
function echoSignal(time,freq){const o=ctx.createOscillator(),delay=ctx.createDelay(),feedback=ctx.createGain(),g=envNode(time,.65,.025);o.type='sine';o.frequency.setValueAtTime(freq,time);o.frequency.linearRampToValueAtTime(freq*1.015,time+.6);delay.delayTime.value=.19;feedback.gain.value=.28;o.connect(g);g.connect(delay);delay.connect(feedback).connect(delay);delay.connect(musicBus);o.start(time);o.stop(time+.68)}
function echoPad(time,root){[0,7,12].forEach((semi,i)=>{const o=ctx.createOscillator(),f=ctx.createBiquadFilter(),g=envNode(time,2.6,.022/(i+1));o.type=i?'sine':'triangle';o.frequency.value=note(root,semi);f.type='lowpass';f.frequency.value=680;f.Q.value=1.8;o.connect(f).connect(g);o.start(time);o.stop(time+2.65)})}
function scheduleMusic(){if(!ctx||!musicBus)return;const m=musicModes[currentMode]||musicModes.hub,beat=60/m.bpm/2;while(nextBeat<ctx.currentTime+.35){const step=musicStep%16,barStep=step%8;
    if(currentMode==='form'){if(step%2===0)bassHit(nextBeat,note(m.root,m.bass[barStep]),step%8===0?1.35:1);if(step%8===0||step%8===5)kick(nextBeat,1.25);if(step%4===2)metalHit(nextBeat,1.25);if(step%8===3||step%8===7)twang(nextBeat,note(m.root,m.lead[barStep]+12))}
    else if(currentMode==='link'){bassHit(nextBeat,note(m.root,m.bass[barStep]),step%4===0?1.1:.7);neonPulse(nextBeat,note(m.root,m.lead[barStep]+12),step%4===0?1.35:.8);if(step%4===0)kick(nextBeat,1.05);if(step%2===1)metalHit(nextBeat,step%4===3?.8:.42)}
    else if(currentMode==='echo'){if(step%4===0)bassHit(nextBeat,note(m.root,m.bass[barStep]-12),1.05);if(step%8===0){darkTom(nextBeat,64);echoPad(nextBeat,note(m.root,step%16===0?0:1))}if(step%8===5)darkTom(nextBeat,52);if(step%2===1)echoSignal(nextBeat,note(m.root,m.lead[barStep]+(step%4===1?12:7)));if(step%8===6)metalHit(nextBeat,.24)}
    else{if(step%4===0)bassHit(nextBeat,note(m.root,m.bass[barStep]),.72);if(step%8===6)twang(nextBeat,note(m.root,m.lead[barStep]));if(step%4===2)metalHit(nextBeat,.28)}
    musicStep++;nextBeat+=beat}}
export function ambient(mode='hub'){if(!enabled||!musicEnabled)return;ctx??=new AudioContext();currentMode=musicModes[mode]?mode:'hub';stopAmbient();musicBus=ctx.createGain();musicBus.gain.value=.15;const compressor=ctx.createDynamicsCompressor();compressor.threshold.value=-18;compressor.knee.value=16;compressor.ratio.value=5;musicBus.connect(compressor).connect(ctx.destination);const o=ctx.createOscillator(),g=ctx.createGain(),f=ctx.createBiquadFilter();o.type='sawtooth';o.frequency.value=musicModes[currentMode].root/2;f.type='lowpass';f.frequency.value=125;g.gain.value=.055;o.connect(f).connect(g).connect(musicBus);o.start();hum={o,g,f};musicStep=0;nextBeat=ctx.currentTime+.06;scheduleMusic();musicTimer=setInterval(scheduleMusic,100)}
export function stopAmbient(){clearInterval(musicTimer);musicTimer=null;hum?.o.stop();hum=null;musicBus?.disconnect();musicBus=null}
