import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.169.0/build/three.module.js';
import {sfx} from './audio.js';

const PALETTES=[
  {sky:0x4b1609,accent:0x31efff,hot:0xff7a18,skin:0x72ba35},
  {sky:0x090526,accent:0xff35b4,hot:0x3ef4ff,skin:0x8348d6},
  {sky:0x020c25,accent:0x35eaff,hot:0x8a4dff,skin:0x477da8}
];
const GEO={box:new THREE.BoxGeometry(1,1,1),ball:new THREE.IcosahedronGeometry(.5,1),cyl:new THREE.CylinderGeometry(.5,.5,1,7),cone:new THREE.ConeGeometry(.5,1,6),ring:new THREE.TorusGeometry(.5,.12,6,12)};

export class GameEngine{
  constructor(canvas,hooks){this.canvas=canvas;this.h=hooks;this.keys={};this.targets=[];this.units=[];this.bolts=[];this.particles=[];this.ray=new THREE.Raycaster();this.clock=new THREE.Clock();this.pitch=0;this.yaw=0;this.active=false;this.shoot=this.shoot.bind(this);this.move=this.move.bind(this);this.key=e=>{this.keys[e.code]=e.type==='keydown';if(e.type==='keydown'&&e.code==='KeyQ')this.h.scan()}}
  init(game){this.dispose();this.game=game;this.p=PALETTES[game];this.scene=new THREE.Scene();this.scene.background=new THREE.Color(this.p.sky);this.scene.fog=new THREE.FogExp2(this.p.sky,.014);this.camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.1,300);this.camera.position.set(0,2.5,9);this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=true;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.makeWorld();addEventListener('resize',this.resize=()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight)});addEventListener('keydown',this.key);addEventListener('keyup',this.key);document.addEventListener('mousemove',this.move);this.canvas.addEventListener('mousedown',this.shoot);this.active=true;this.animate()}
  mat(color,emissive=0){return new THREE.MeshStandardMaterial({color,emissive,emissiveIntensity:emissive?.35:0,roughness:.62,metalness:.22,flatShading:true})}
  mesh(geo,mat,pos,scale=[1,1,1],parent=this.scene){const m=new THREE.Mesh(geo,mat);m.position.set(...pos);m.scale.set(...scale);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
  outline(mesh,scale=1.08){const o=new THREE.Mesh(mesh.geometry,new THREE.MeshBasicMaterial({color:0x020407,side:THREE.BackSide}));o.position.copy(mesh.position);o.rotation.copy(mesh.rotation);o.scale.copy(mesh.scale).multiplyScalar(scale);mesh.parent.add(o);o.renderOrder=-1;return o}
  landscapeTexture(){const cv=document.createElement('canvas');cv.width=cv.height=1024;const x=cv.getContext('2d'),base=['#713719','#171d46','#142e55'][this.game],hot=['#b85a20','#65258b','#284e82'][this.game];x.fillStyle=base;x.fillRect(0,0,1024,1024);for(let i=0;i<150;i++){x.fillStyle=i%7?hot:this.game===0?'#a7e51b':this.p.accent===0xff35b4?'#ff35b4':'#35eaff';x.beginPath();const px=Math.random()*1024,py=Math.random()*1024,r=12+Math.random()*65;x.moveTo(px-r,py);for(let j=0;j<7;j++){const a=j/7*Math.PI*2;x.lineTo(px+Math.cos(a)*r*(.5+Math.random()),py+Math.sin(a)*r*(.5+Math.random()))}x.fill();x.strokeStyle='#07101a';x.lineWidth=8;x.stroke()}for(let i=0;i<25;i++){x.strokeStyle=i%3?this.game===0?'#b9ff2c':'#3ef5ff':'#ff36ac';x.lineWidth=4+Math.random()*9;x.shadowColor=x.strokeStyle;x.shadowBlur=14;x.beginPath();x.moveTo(Math.random()*1024,Math.random()*1024);for(let j=0;j<6;j++)x.lineTo(Math.random()*1024,Math.random()*1024);x.stroke()}const t=new THREE.CanvasTexture(cv);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(7,7);t.colorSpace=THREE.SRGBColorSpace;return t}
  chromaSprite(file,pos,scale){new THREE.TextureLoader().load(`assets/images/${file}`,source=>{if(!this.scene)return;const img=source.image,cv=document.createElement('canvas');cv.width=img.width;cv.height=img.height;const cx=cv.getContext('2d',{willReadFrequently:true});cx.drawImage(img,0,0);const px=cx.getImageData(0,0,cv.width,cv.height),d=px.data;for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2],key=g-Math.max(r,b);if(g>115&&key>45)d[i+3]=Math.max(0,255-(key-45)*5)}cx.putImageData(px,0,0);const tex=new THREE.CanvasTexture(cv);tex.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,alphaTest:.08,depthWrite:false}));sprite.position.set(...pos);sprite.scale.set(...scale,1);sprite.renderOrder=1;this.scene.add(sprite)})}
  makeWorld(){const p=this.p;new THREE.TextureLoader().load(`assets/images/${['verb-wastes','neon-city','echo-station'][this.game]}.png`,t=>{t.colorSpace=THREE.SRGBColorSpace;this.scene.background=t});this.scene.add(new THREE.HemisphereLight(0x9edbff,0x160610,1.7));const sun=new THREE.DirectionalLight(0xffffff,2.5);sun.position.set(-8,18,10);sun.castShadow=true;this.scene.add(sun);const rim=new THREE.PointLight(p.accent,35,35);rim.position.set(0,8,-10);this.scene.add(rim);
    if(this.game===0){const groundMat=this.mat(0xffffff);groundMat.map=this.landscapeTexture();groundMat.emissive.set(0x291107);groundMat.emissiveIntensity=.25;groundMat.transparent=true;groundMat.opacity=.26;const ground=this.mesh(new THREE.PlaneGeometry(180,180,32,32),groundMat,[0,0,0]);ground.rotation.x=-Math.PI/2}
    for(let i=0;i<38;i++){const side=i%2?-1:1,x=side*(11+Math.random()*38),z=-2-Math.random()*90;if(this.game===0){const rock=this.mesh(GEO.cone,this.mat(i%4?p.hot:0x85d42b),[x,2+Math.random()*3,z],[2+Math.random()*3,5+Math.random()*8,2+Math.random()*3]);rock.rotation.z=(Math.random()-.5)*.35}}
    if(this.game===1){const props=[[-15,7,-12,8,14,1],[-24,9,-27,10,18,2],[-19,6,-44,11,10,2],[-32,11,-62,12,22,1],[-14,8,-78,10,17,1],[15,7,-13,8,14,1],[24,8,-29,12,12,2],[18,10,-46,11,20,1],[31,7,-64,13,11,2],[15,9,-82,10,18,1]];props.forEach(([x,y,z,w,h,type])=>this.chromaSprite(`neon-city-prop-${type}-source.png`,[x,y,z],[w,h]))}
    if(this.game===2){const props=[[-15,6,-12,9,12,1],[-24,8,-27,13,15,2],[-18,7,-44,11,14,3],[-31,9,-63,15,18,2],[-15,7,-81,11,15,1],[15,6,-13,9,12,3],[25,8,-30,14,16,1],[18,7,-47,12,14,2],[31,9,-65,15,18,3],[15,7,-83,11,15,2]];props.forEach(([x,y,z,w,h,type])=>this.chromaSprite(`echo-prop-${type}-source.png`,[x,y,z],[w,h]))}
    for(let i=0;i<90;i++){const s=this.mesh(GEO.ball,new THREE.MeshBasicMaterial({color:i%4?p.accent:p.hot}),[(Math.random()-.5)*90,1+Math.random()*25,-Math.random()*100],[.04,.04,.04]);s.userData.float=Math.random()*6;this.particles.push(s)}
  }
  label(text){const echo=this.game===2,cv=document.createElement('canvas');cv.width=echo?1400:1024;cv.height=echo?360:220;const x=cv.getContext('2d');x.shadowColor='#000';x.shadowBlur=16;x.fillStyle='#06101eee';x.strokeStyle='#70f6ff';x.lineWidth=12;x.beginPath();x.roundRect(12,12,cv.width-24,cv.height-24,34);x.fill();x.stroke();x.fillStyle='#fff';x.textAlign='center';x.textBaseline='middle';if(echo){let fontSize=72,words=text.split(' '),lines=[];do{lines=[];let line='';x.font=`900 ${fontSize}px Arial`;words.forEach(word=>{const test=line?`${line} ${word}`:word;if(x.measureText(test).width>1240&&line){lines.push(line);line=word}else line=test});if(line)lines.push(line);if(lines.length<=4)break;fontSize-=3}while(fontSize>52);const lineHeight=fontSize*.98,start=cv.height/2-(lines.length-1)*lineHeight/2;lines.forEach((line,i)=>x.fillText(line,cv.width/2,start+i*lineHeight,1240))}else{x.font=`900 ${text.length>22?52:66}px Arial`;x.fillText(text.length>34?text.slice(0,33)+'…':text,512,112)}const t=new THREE.CanvasTexture(cv);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false}));s.scale.set(echo?7.25:6.2,echo?1.86:1.34,1);s.renderOrder=30;return s}
  bossLabel(text){const cv=document.createElement('canvas');cv.width=1400;cv.height=300;const x=cv.getContext('2d');x.shadowColor='#000';x.shadowBlur=22;x.fillStyle='#06101ef5';x.strokeStyle=this.game===2?'#ffb52e':this.game===1?'#62f7ff':'#9dff43';x.lineWidth=18;x.beginPath();x.roundRect(18,18,1364,264,46);x.fill();x.stroke();x.fillStyle='#fff';let fontSize=94;const maxTextWidth=1180;do{x.font=`900 ${fontSize}px Arial`;if(x.measureText(text).width<=maxTextWidth)break;fontSize-=2}while(fontSize>42);x.textAlign='center';x.textBaseline='middle';x.fillText(text,700,153,maxTextWidth);const t=new THREE.CanvasTexture(cv);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false}));s.renderOrder=45;return s}
  part(parent,geo,color,pos,scale,outline=true){const m=this.mesh(geo,this.mat(color,color===this.p.accent?color:0),pos,scale,parent);if(outline)this.outline(m);return m}
  enemy(answer,index,boss=false){const u=new THREE.Group(),p=this.p,type=(index+this.wave+this.game)%6,lanes=[[-8.8,-7.2],[-.8,.8],[7.2,8.8]],lane=lanes[index],wraith=this.game===2;u.position.set((lane[0]+lane[1])/2,wraith ? .15 : index%2 ? 1.85 : 1.25,wraith ? -9 : -7);u.userData={phase:Math.random()*6,minX:lane[0],maxX:lane[1],minY:index%2 ? 1.45 : 1.05,maxY:index%2 ? 2.25 : 1.75,vx:(Math.random()>.5?1:-1)*(.75+Math.random()*.65),vy:(Math.random()>.5?1:-1)*(.3+Math.random()*.4),drone:this.game===1,wraith,baseScale:boss?1.05:1};if(u.userData.drone){u.userData.vx=0;u.userData.vy=0;const glow=new THREE.PointLight(0xff35b4,3.5,boss?13:9);glow.position.set(0,boss?2.6:2.1,1);u.add(glow);u.userData.glow=glow}this.scene.add(u);
    const core=this.part(u,boss?GEO.ball:GEO.box,boss?0x27233e:p.skin,[0,boss?2.2:1.65,0],boss?[2.1,2.1,1.35]:[1.15,1.35,.72]);core.userData={answer,target:true,boss,unit:u};this.targets.push(core);
    const head=this.part(u,type===0?GEO.ball:type===1?GEO.box:GEO.cone,0x25344a,[0,boss?4.15:3.05,.03],boss?[1.25,1.1,1]:[.78,.72,.7]);
    const visor=this.part(u,GEO.box,p.accent,[0,boss?4.22:3.12,.63],boss?[.85,.25,.12]:[.55,.16,.1],false);visor.material.emissiveIntensity=2.2;
    for(const side of [-1,1]){const shoulder=this.part(u,type===2?GEO.cone:GEO.ball,p.hot,[side*(boss?2.05:1.18),boss?3.05:2.35,0],boss?[.8,.8,.8]:[.56,.56,.56]);shoulder.rotation.z=side*(type===2?.7:0);const upper=this.part(u,GEO.cyl,0x2b3a4d,[side*(boss?2.2:1.28),boss?2.15:1.55,0],boss?[.42,1.4,.42]:[.27,1,.27]);upper.rotation.z=side*.18;const claw=this.part(u,type?GEO.cone:GEO.ball,p.accent,[side*(boss?2.45:1.42),boss?1.1:.78,.05],boss?[.6,.9,.6]:[.38,.58,.38]);claw.rotation.z=side*Math.PI;
      const leg=this.part(u,GEO.cyl,0x263247,[side*(boss ? .85 : .48),boss ? .25 : .28,0],boss?[.5,1.6,.5]:[.3,1.25,.3]);leg.rotation.z=side*.08;this.part(u,GEO.box,p.hot,[side*(boss ? .95 : .54),boss ? -.7 : -.34,.25],boss?[.8,.35,1.15]:[.52,.25,.8]);}
    if(type===0){for(let i=0;i<4;i++){const horn=this.part(u,GEO.cone,p.hot,[(i-1.5)*.38,boss?5.1:3.78,0],[.18,.65,.18]);horn.rotation.z=(i-1.5)*.2}}
    if(type===1){const pack=this.part(u,GEO.box,0x18202d,[0,boss?2.6:2,.78],boss?[1.5,1.6,.45]:[.9,1,.4]);for(const side of [-1,1])this.part(u,GEO.cyl,p.accent,[side*(boss?1.4:.8),boss?3.1:2.3,.95],[.11,1.3,.11])}
    if(type===2){const ring=this.part(u,GEO.ring,p.accent,[0,boss?2.3:1.8,.9],boss?[1.6,1.6,1.6]:[.9,.9,.9],false);ring.rotation.x=Math.PI/2}
    const lbl=this.label(answer);lbl.position.set(0,boss?5.5:this.game===2?5.78:4.45,.55);lbl.userData={answer,target:true,boss,unit:u,hitMesh:core};u.add(lbl);this.targets.push(lbl);const artFile=this.game===1?`phrasal-drone-${type%3+1}-source.png`:this.game===2?`echo-wraith-${type%3+1}-source.png`:`monster-${type+1}-source.png`;new THREE.TextureLoader().load(`assets/images/${artFile}`,source=>{const img=source.image,cv=document.createElement('canvas');cv.width=img.width;cv.height=img.height;const cx=cv.getContext('2d',{willReadFrequently:true});cx.drawImage(img,0,0);const px=cx.getImageData(0,0,cv.width,cv.height),d=px.data;for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2],key=g-Math.max(r,b);if(g>115&&key>45)d[i+3]=Math.max(0,255-(key-45)*5)}cx.putImageData(px,0,0);const tex=new THREE.CanvasTexture(cv);tex.colorSpace=THREE.SRGBColorSpace;const art=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,alphaTest:.08}));art.scale.set(boss?7.2:5.2,boss?7.2:5.2,1);art.position.set(0,boss?2.6:2.15,.7);art.userData={answer,target:true,boss,unit:u,hitMesh:core};u.add(art);this.targets.push(art);u.children.forEach(c=>{if(c.isMesh)c.visible=false})});u.scale.setScalar(u.userData.baseScale);this.units.push(u);return u}
  spawn(answers,boss=false){this.clearTargets();this.wave=((this.wave||0)+1)%6;answers.forEach((a,i)=>this.enemy(a,i,boss))}
  bossAnswerLabels(unit,answers){
    unit.userData.answerLabels?.forEach(label=>unit.remove(label));
    this.targets=this.targets.filter(target=>!target.userData.bossAnswer);
    const spacing=this.game===2?8.2:7.35,width=this.game===2?7.25:6.65,height=this.game===2?1.62:1.48;
    unit.userData.answerLabels=answers.map((answer,index)=>{const label=this.bossLabel(answer);label.position.set((index-1)*spacing,.4,1.3);label.scale.set(width,height,1);label.userData={answer,target:true,boss:true,bossAnswer:true,unit};unit.add(label);this.targets.push(label);return label});
  }
  spawnSoloBoss(answers,artFile='regretter-boss-source.png'){
    this.clearTargets();
    const unit=new THREE.Group();unit.position.set(0,.15,-8);unit.userData={phase:Math.random()*6,baseScale:1,bossOnly:true,answerLabels:[]};this.scene.add(unit);this.units.push(unit);
    new THREE.TextureLoader().load(`assets/images/${artFile}`,source=>{if(!this.scene||!unit.parent)return;const img=source.image,cv=document.createElement('canvas');cv.width=img.width;cv.height=img.height;const cx=cv.getContext('2d',{willReadFrequently:true});cx.drawImage(img,0,0);const px=cx.getImageData(0,0,cv.width,cv.height),d=px.data;for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2],key=g-Math.max(r,b);if(g>110&&key>38)d[i+3]=Math.max(0,255-(key-38)*5.6)}cx.putImageData(px,0,0);const tex=new THREE.CanvasTexture(cv);tex.colorSpace=THREE.SRGBColorSpace;const art=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,alphaTest:.06}));art.position.set(0,4.15,0);art.scale.set(9.2,9.2,1);art.renderOrder=2;unit.add(art);unit.userData.art=art});
    const glow=new THREE.PointLight(this.game===1?0xff35b4:0xff5a16,55,24);glow.position.set(0,4,2);unit.add(glow);unit.userData.glow=glow;this.bossAnswerLabels(unit,answers);
  }
  updateSoloBoss(answers){const unit=this.units.find(x=>x.userData.bossOnly);if(unit)this.bossAnswerLabels(unit,answers)}
  damageSoloBoss(){const unit=this.units.find(x=>x.userData.bossOnly);if(!unit)return;unit.userData.hit=1;if(this.game!==2)this.burst(new THREE.Vector3(unit.position.x,unit.position.y+4,unit.position.z+1),this.game===1?0x42f6ff:0xff7a18,34);if(this.game===1)this.electricHit(unit)}
  explodeSoloBoss(done){const unit=this.units.find(x=>x.userData.bossOnly);if(!unit){done?.();return}this.targets=[];unit.userData.answerLabels?.forEach(x=>x.visible=false);let blasts=0;const timer=setInterval(()=>{if(!this.scene||!unit.parent){clearInterval(timer);return}const pos=new THREE.Vector3(unit.position.x+(Math.random()-.5)*5,unit.position.y+1+Math.random()*6,unit.position.z+1);if(this.game!==2)this.burst(pos,blasts%2?0xff35b4:0x42f6ff,42);unit.scale.multiplyScalar(1.035);if(unit.userData.art)unit.userData.art.material.opacity=Math.max(0,1-blasts/8);unit.userData.glow.intensity=80+blasts*25;if(++blasts>=9){clearInterval(timer);setTimeout(()=>{this.scene?.remove(unit);done?.()},300)}},90)}
  burst(pos,color,count=18){for(let i=0;i<count;i++){const p=this.mesh(GEO.ball,new THREE.MeshBasicMaterial({color}),[pos.x,pos.y,pos.z],[.08,.08,.08]);p.userData.vel=new THREE.Vector3((Math.random()-.5)*7,(Math.random()-.1)*6,(Math.random()-.5)*7);p.userData.life=.7;this.bolts.push(p)}}
  clearTargets(){this.units?.forEach(x=>this.scene?.remove(x));this.targets=[];this.units=[]}
  move(e){if(!this.active||document.pointerLockElement!==this.canvas)return;this.yaw-=e.movementX*.002;this.pitch=Math.max(-1.1,Math.min(1.1,this.pitch-e.movementY*.002));this.camera.rotation.set(this.pitch,this.yaw,0,'YXZ')}
  shoot(e){if(!this.active)return;this.game===1?sfx.electric():this.game===2?sfx.flame():sfx.shot();document.dispatchEvent(new CustomEvent('lexa-shot',{detail:{x:e.clientX,y:e.clientY}}));const rect=this.canvas.getBoundingClientRect(),pointer=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-((e.clientY-rect.top)/rect.height)*2+1);this.ray.setFromCamera(pointer,this.camera);const hit=this.ray.intersectObjects(this.targets,false)[0];if(hit){if(this.game!==2)this.burst(hit.point,this.p.accent);this.h.hit(hit.object.userData,hit.object)}}
  electricHit(unit){const center=new THREE.Vector3(unit.position.x,unit.position.y+(unit.userData.bossOnly?4:2.5),unit.position.z+1),radius=unit.userData.bossOnly?4.2:2.5,flash=new THREE.PointLight(0xbafcff,150,22);flash.position.copy(center);this.scene.add(flash);setTimeout(()=>this.scene?.remove(flash),240);for(let n=0;n<14;n++){const points=[],start=Math.random()*Math.PI*2;for(let i=0;i<10;i++){const t=i/9,angle=start+t*Math.PI*(1.2+Math.random()*.7),r=radius*(.72+Math.random()*.34);points.push(new THREE.Vector3(center.x+Math.cos(angle)*r+(Math.random()-.5)*.5,center.y+(t-.5)*radius*2.1+(Math.random()-.5)*.65,center.z+Math.sin(angle)*r*.32))}const material=new THREE.LineBasicMaterial({color:n%3===0?0xffffff:n%2?0x42f6ff:0xc53dff,transparent:true,opacity:1,blending:THREE.AdditiveBlending,depthWrite:false}),line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),material);line.renderOrder=40;this.scene.add(line);setTimeout(()=>{this.scene?.remove(line);material.dispose();line.geometry.dispose()},170+Math.random()*170)}for(let ringIndex=0;ringIndex<3;ringIndex++){const ring=new THREE.Mesh(GEO.ring,new THREE.MeshBasicMaterial({color:ringIndex===1?0xff45e6:0x7bffff,transparent:true,opacity:.9,blending:THREE.AdditiveBlending,depthWrite:false}));ring.position.copy(center);ring.scale.setScalar(radius*(.75+ringIndex*.22));ring.rotation.set(Math.random()*Math.PI,Math.random()*Math.PI,Math.random()*Math.PI);ring.renderOrder=39;this.scene.add(ring);setTimeout(()=>this.scene?.remove(ring),170+ringIndex*55)}for(let i=0;i<8;i++)setTimeout(()=>this.burst(new THREE.Vector3(center.x+(Math.random()-.5)*radius*1.7,center.y+(Math.random()-.5)*radius*1.8,center.z+(Math.random()-.5)),i%2?0xffffff:0x42f6ff,24),i*28)}
  flash(obj,correct){const hit=obj.userData.hitMesh||obj;if(hit.material?.emissive){hit.material.emissive.set(correct?0x34ff91:0xff173d);hit.material.emissiveIntensity=4;setTimeout(()=>{if(hit.material)hit.material.emissiveIntensity=.2},180)}obj.userData.unit.userData.hit=1;if(this.game===1)this.electricHit(obj.userData.unit)}
  animate(){if(!this.active)return;requestAnimationFrame(()=>this.animate());const d=Math.min(this.clock.getDelta(),.04),time=performance.now()*.001,speed=(this.keys.ShiftLeft?16:7)*d,v=new THREE.Vector3();if(this.keys.KeyW)v.z-=speed;if(this.keys.KeyS)v.z+=speed;if(this.keys.KeyA)v.x-=speed;if(this.keys.KeyD)v.x+=speed;v.applyAxisAngle(new THREE.Vector3(0,1,0),this.yaw);this.camera.position.add(v);this.camera.position.x=Math.max(-14,Math.min(14,this.camera.position.x));this.camera.position.z=Math.max(-1,Math.min(16,this.camera.position.z));if(this.keys.Space&&this.camera.position.y<=2.51)this.jump=5.5;this.jump=(this.jump||0)-13*d;this.camera.position.y=Math.max(2.5,this.camera.position.y+this.jump*d);
    this.units.forEach((u,i)=>{const phase=u.userData.phase;if(u.userData.bossOnly){if(!u.userData.hit)u.position.y=.15+Math.sin(time*1.4+phase)*.06;if(u.userData.glow)u.userData.glow.intensity=55+Math.sin(time*2.4)*10}else if(u.userData.wraith){u.position.z=Math.min(-3.8,u.position.z+d*.22);u.position.y=.15+Math.abs(Math.sin(time*.72+phase))*.045;u.position.x+=Math.sin(time*.55+phase)*d*.025;u.rotation.y=0;u.scale.setScalar(u.userData.baseScale*(1+Math.sin(time*.72+phase)*.008))}else if(!u.userData.drone){u.position.x+=u.userData.vx*d;u.position.y+=u.userData.vy*d;if(u.position.x>u.userData.maxX||u.position.x<u.userData.minX)u.userData.vx*=-1;if(u.position.y>u.userData.maxY||u.position.y<u.userData.minY)u.userData.vy*=-1;u.rotation.y=Math.sin(time*.8+phase)*.08}else{const pulse=1+Math.sin(time*2.1+phase)*.018;u.scale.setScalar(u.userData.baseScale*pulse);u.rotation.y=0;if(u.userData.glow)u.userData.glow.intensity=3.2+Math.sin(time*2.1+phase)*.7}u.children.forEach((c,j)=>{if(c.type==='Mesh'&&j>3)c.rotation.x+=Math.sin(time*3+phase+j)*.002});if(u.userData.hit){u.rotation.z=(Math.random()-.5)*.18*u.userData.hit;u.userData.hit=Math.max(0,u.userData.hit-d*5)}else u.rotation.z=0});
    this.particles.forEach((p,i)=>{p.position.y+=Math.sin(time+p.userData.float)*.004;p.rotation.y+=d});this.bolts.forEach((b,i)=>{b.position.addScaledVector(b.userData.vel,d);b.userData.life-=d;if(b.userData.life<=0){this.scene.remove(b);this.bolts.splice(i,1)}});this.renderer.render(this.scene,this.camera)}
  dispose(){this.active=false;this.clearTargets?.();removeEventListener('resize',this.resize);removeEventListener('keydown',this.key);removeEventListener('keyup',this.key);document.removeEventListener('mousemove',this.move);this.canvas.removeEventListener('mousedown',this.shoot);this.renderer?.dispose()}
}
