const portrait=document.querySelector('#heroPortrait');
const proxy=document.querySelector('#heroAvatar');
const renameHeroes=root=>{const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode())node.nodeValue=node.nodeValue.replaceAll('KAEL','TOPKRENDEL').replaceAll('NYRA','PANGVA').replaceAll('Kael','TOPKRENDEL').replaceAll('Nyra','PANGVA')};renameHeroes(document.body);new MutationObserver(records=>records.forEach(record=>record.addedNodes.forEach(node=>renameHeroes(node.nodeType===Node.TEXT_NODE?node.parentNode:node)))).observe(document.body,{subtree:true,childList:true});
const syncPortrait=()=>{const hero=proxy.classList.contains('nyra')?'nyra':'kael';portrait.src=`assets/images/${hero}.png?v=4`;portrait.className=hero};
new MutationObserver(syncPortrait).observe(proxy,{attributes:true,attributeFilter:['class']});
syncPortrait();
document.addEventListener('pointermove',e=>{const screen=document.querySelector('.screen.active');if(!screen||!['select','hub'].includes(screen.id))return;const x=(e.clientX/innerWidth-.5)*10,y=(e.clientY/innerHeight-.5)*6;const bg=screen.querySelector('.select-bg,.hub-scenery');if(bg)bg.style.transform=`scale(1.05) translate(${x}px,${y}px)`});
document.querySelectorAll('.hunter').forEach(card=>{card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateY(${x*8}deg) rotateX(${-y*6}deg) translateY(-5px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
const cards=document.querySelector('#cards'),missionArt=['verb-wastes','neon-city','echo-station'];
new MutationObserver(()=>cards.querySelectorAll('.card-art').forEach((art,i)=>{art.style.backgroundImage=`linear-gradient(0deg,#07111b 3%,transparent 72%),url('assets/images/${missionArt[i]}.png')`;art.style.backgroundSize='cover';art.style.backgroundPosition='center'})).observe(cards,{childList:true});
const drawKeyedHero=(canvas,hero)=>{const img=new Image(),file=hero==='nyra'?'nyra-reward-source.png':'kael-reward-source.png';img.src=`assets/images/${file}?v=4`;img.onload=()=>{canvas.width=img.width;canvas.height=img.height;const cx=canvas.getContext('2d',{willReadFrequently:true});cx.clearRect(0,0,img.width,img.height);cx.drawImage(img,0,0);const px=cx.getImageData(0,0,img.width,img.height),d=px.data;for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2],key=g-Math.max(r,b);if(g>95&&key>28){d[i+3]=Math.max(0,255-(key-28)*5.8);d[i+1]=Math.min(g,Math.max(r,b)+8)}}cx.putImageData(px,0,0)}};const rewardHero=document.querySelector('#rewardHero');window.setRewardHero=hero=>drawKeyedHero(rewardHero,hero);window.setSecretRewardHero=hero=>drawKeyedHero(document.querySelector('#secretRewardHero'),hero);Object.defineProperty(rewardHero,'src',{configurable:true,set(value){window.setRewardHero(value.includes('nyra')?'nyra':'kael')}});window.setRewardHero('kael');
const rewardWeapon=document.querySelector('#rewardWeapon');window.setRewardItem=file=>{const rewardImage=new Image();rewardImage.src=`assets/images/${file}`;rewardImage.onload=()=>{rewardWeapon.width=rewardImage.width;rewardWeapon.height=rewardImage.height;const cx=rewardWeapon.getContext('2d',{willReadFrequently:true});cx.clearRect(0,0,rewardWeapon.width,rewardWeapon.height);cx.drawImage(rewardImage,0,0);const px=cx.getImageData(0,0,rewardWeapon.width,rewardWeapon.height),d=px.data;for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2],key=g-Math.max(r,b);if(g>110&&key>38){d[i+3]=Math.max(0,255-(key-38)*5.6);d[i+1]=Math.min(g,Math.max(r,b)+10)}}cx.putImageData(px,0,0)}};window.setRewardItem('riftbreaker-shotgun-source.png');
const rewardScreen=document.querySelector('#formReward'),rewardReturn=document.querySelector('.reward-return');new MutationObserver(()=>{rewardReturn.textContent=rewardScreen.classList.contains('reward-echo')?'CONTINUE TO THE PALACE':'RETURN TO MISSION SELECT'}).observe(rewardScreen,{attributes:true,attributeFilter:['class']});
const weapon=document.querySelector('#weaponOverlay');window.setMissionWeapon=mission=>{const weaponImage=new Image(),file=mission==='link'?'riftbreaker-fps-source.png':mission==='echo'?'echo-flamethrower-fps-source.png':'blaster-source.png';weaponImage.src=`assets/images/${file}`;weaponImage.onload=()=>{weapon.width=weaponImage.width;weapon.height=weaponImage.height;const cx=weapon.getContext('2d',{willReadFrequently:true});cx.clearRect(0,0,weapon.width,weapon.height);cx.drawImage(weaponImage,0,0);const px=cx.getImageData(0,0,weapon.width,weapon.height),d=px.data;for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2],key=g-Math.max(r,b);if(g>110&&key>38){d[i+3]=Math.max(0,255-(key-38)*5.6);d[i+1]=Math.min(g,Math.max(r,b)+10)}}cx.putImageData(px,0,0)}};window.setMissionWeapon('form');
const lightning=document.querySelector('#lightningFx'),lightningGroup=lightning.querySelector('g'),sparkLayer=document.querySelector('#electricSparks');
const fireLayer=document.querySelector('#fireFx');
function electricPath(sx,sy,tx,ty,spread=22,steps=11){const dx=tx-sx,dy=ty-sy,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len;let path=`M ${sx} ${sy}`;for(let i=1;i<steps;i++){const t=i/steps,fade=Math.sin(Math.PI*t),jitter=(Math.random()-.5)*spread*fade;path+=` L ${sx+dx*t+nx*jitter} ${sy+dy*t+ny*jitter}`}return path+` L ${tx} ${ty}`}
function addElectricPath(d,cls){const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',d);path.setAttribute('class',cls);lightningGroup.append(path)}
function fireLightning(sx,sy,tx,ty){lightning.setAttribute('viewBox',`0 0 ${innerWidth} ${innerHeight}`);lightningGroup.innerHTML='';[[42,'electric-halo'],[29,'electric-arc'],[15,'electric-core']].forEach(([spread,cls],i)=>addElectricPath(electricPath(sx,sy,tx,ty,spread,14+i),cls));const rx=Math.max(72,Math.min(145,innerWidth*.095)),ry=Math.max(105,Math.min(225,innerHeight*.24)),nodes=[];for(let i=0;i<16;i++){const a=-Math.PI/2+i*Math.PI*2/16,n={x:tx+Math.cos(a)*rx*(.72+Math.random()*.28),y:ty+Math.sin(a)*ry*(.72+Math.random()*.28)};nodes.push(n)}for(let i=0;i<nodes.length;i++){const a=nodes[i],b=nodes[(i+1)%nodes.length],cross=nodes[(i+5+Math.floor(Math.random()*5))%nodes.length];addElectricPath(electricPath(a.x,a.y,b.x,b.y,22,6),'electric-web');addElectricPath(electricPath(a.x,a.y,cross.x,cross.y,28,8),i%3?'electric-web':'electric-core')}for(let i=0;i<10;i++){const a=nodes[Math.floor(Math.random()*nodes.length)],ang=Math.atan2(a.y-ty,a.x-tx),len=30+Math.random()*75;addElectricPath(electricPath(a.x,a.y,a.x+Math.cos(ang)*len,a.y+Math.sin(ang)*len,13,5),'electric-branch')}lightning.classList.remove('fire');void lightning.offsetWidth;lightning.classList.add('fire');sparkLayer.innerHTML='';const aura=document.createElement('strong');aura.style.left=tx+'px';aura.style.top=ty+'px';aura.style.setProperty('--aura-w',rx*2+'px');aura.style.setProperty('--aura-h',ry*2+'px');sparkLayer.append(aura);for(let i=0;i<74;i++){const spark=document.createElement('i'),angle=Math.random()*Math.PI*2,distance=30+Math.random()*Math.max(rx,ry);spark.style.left=tx+'px';spark.style.top=ty+'px';spark.style.setProperty('--spark-x',Math.cos(angle)*distance+'px');spark.style.setProperty('--spark-y',Math.sin(angle)*distance+'px');spark.style.setProperty('--spark-r',angle*180/Math.PI+90+'deg');spark.style.animationDelay=Math.random()*.12+'s';sparkLayer.append(spark)}setTimeout(()=>{lightningGroup.innerHTML='';sparkLayer.innerHTML=''},680)}
function fireStream(sx,sy,tx,ty){fireLayer.innerHTML='';const dx=tx-sx,dy=ty-sy,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len;for(let i=0;i<68;i++){const flame=document.createElement('i'),t=.04+Math.random()*.96,spread=(8+48*t)*(Math.random()-.5),x=dx*t+nx*spread,y=dy*t+ny*spread,size=18+Math.random()*34*(.4+t);flame.className='stream-flame';flame.style.left=sx+'px';flame.style.top=sy+'px';flame.style.width=size+'px';flame.style.height=size*(1.25+Math.random()*.55)+'px';flame.style.setProperty('--fire-x',x+'px');flame.style.setProperty('--fire-y',y+'px');flame.style.setProperty('--fire-r',(Math.random()-.5)*16+'deg');flame.style.animationDelay=Math.random()*.11+'s';fireLayer.append(flame)}for(let i=0;i<46;i++){const flame=document.createElement('i'),a=Math.random()*Math.PI*2,radX=18+Math.random()*110,radY=24+Math.random()*185,size=38+Math.random()*74;flame.className='enemy-flame';flame.style.left=tx+Math.cos(a)*radX+'px';flame.style.top=ty+Math.sin(a)*radY*.7+55+'px';flame.style.width=size+'px';flame.style.height=size*(1.1+Math.random()*.7)+'px';flame.style.setProperty('--fire-r',(Math.random()-.5)*18+'deg');flame.style.animationDelay=.06+Math.random()*.2+'s';fireLayer.append(flame)}const blast=document.createElement('strong');blast.className='fire-blast';blast.style.left=tx+'px';blast.style.top=ty+'px';fireLayer.append(blast);fireLayer.classList.remove('fire');void fireLayer.offsetWidth;fireLayer.classList.add('fire');setTimeout(()=>fireLayer.innerHTML='',900)}
document.addEventListener('lexa-shot',e=>{const game=document.querySelector('#game'),link=game.classList.contains('game-link'),echo=game.classList.contains('game-echo'),r=weapon.getBoundingClientRect(),fps=link||echo,sx=fps?r.left+r.width*.5:r.left+r.width*.5,sy=fps?r.top+r.height*.045:r.top+r.height*.22,dx=e.detail.x-sx,dy=e.detail.y-sy,len=Math.hypot(dx,dy),angle=Math.atan2(dy,dx)*180/Math.PI,beam=document.querySelector('#beam'),flash=document.querySelector('#muzzleFlash'),flashRadius=echo?65:45;if(link){beam.classList.remove('fire');fireLightning(sx,sy,e.detail.x,e.detail.y)}else if(echo){beam.classList.remove('fire');fireStream(sx,sy,e.detail.x,e.detail.y)}else{beam.style.left=sx+'px';beam.style.top=sy+'px';beam.style.width=len+'px';beam.style.setProperty('--beam-transform',`rotate(${angle}deg)`);beam.classList.remove('fire');void beam.offsetWidth;beam.classList.add('fire')}flash.style.left=sx-flashRadius+'px';flash.style.top=sy-flashRadius+'px';flash.classList.remove('fire');void flash.offsetWidth;flash.classList.add('fire');weapon.animate([{transform:'translateY(0) scale(1)'},{transform:'translateY(-30px) scale(1.04)'},{transform:'translateY(-9px) scale(1.018)'},{transform:'translateY(0) scale(1)'}],{duration:280,easing:'cubic-bezier(.2,.8,.25,1)'})});
