const TASKS=[
  {answer:'TOOK OFF',a:'The plane ______ twenty minutes late yesterday.',b:'He ______ his boots when he entered the house.'},
  {answer:'BROKE DOWN',a:'Our washing machine ______ again yesterday.',b:'Maya ______ when she heard what had happened.'},
  {answer:'PICKS UP',a:'Our courier ______ the parcel from the station every morning.',b:'Business usually ______ before Christmas.'},
  {answer:'TURNED DOWN',a:'She ______ the job offer because the salary was too low.',b:'He ______ the music when the baby fell asleep.'},
  {answer:'WORKS OUT',a:'Maya usually ______ how to open security systems.',b:'He ______ at the gym four times a week.'},
  {answer:'TOOK UP',a:'Maya ______ painting during the winter.',b:'The old machine ______ half the room before we removed it.'},
  {answer:'BROUGHT UP',a:'She was ______ by her grandparents.',b:'The manager ______ that subject during the meeting.'},
  {answer:'RAN INTO',a:'I ______ my old English teacher in town yesterday.',b:'The project ______ serious financial problems last month.'},
  {answer:'SETS OFF',a:'Our convoy usually ______ before sunrise to avoid the traffic.',b:'Smoke from this machine often ______ the fire alarm.'},
  {answer:'LOOKED UP',a:'I ______ the word in a dictionary yesterday.',b:'Things finally ______ for the company after the new contract.'},
  {answer:'PUTS DOWN',a:'He always ______ the box before opening the door.',b:'She constantly ______ her rivals to make herself feel better.'},
  {answer:'MADE UP',a:'He ______ an excuse for being late yesterday.',b:'Women ______ more than half of the research team in 2024.'}
];

export class BlackMarketMission{
  constructor(root,{onComplete,onExit,sfx}={}){this.root=root;this.onComplete=onComplete;this.onExit=onExit;this.sfx=sfx;this.index=0;this.value='';this.locked=false;this.integrity=3;this.timer=null;this.bind()}
  bind(){const input=this.root.querySelector('.market-input');input.addEventListener('input',()=>{input.value=input.value.toUpperCase().replace(/[^A-Z ]/g,'').replace(/\s+/g,' ').replace(/^ /,'');this.value=input.value});input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();this.verify()}});this.root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.marketAction==='begin')this.begin();if(b.dataset.marketAction==='verify')this.verify();if(b.dataset.marketAction==='verb')this.hint('verb');if(b.dataset.marketAction==='particle')this.hint('particle');if(b.dataset.marketAction==='exit')this.exit()})}
  play(hero='KAEL'){this.clear();this.index=0;this.value='';this.integrity=3;this.root.dataset.hero=hero.toLowerCase();this.root.dataset.stage='intro';const display=hero==='NYRA'?'PANGVA':'TOPKRENDEL';this.root.querySelector('.market-intro-name').textContent=display;this.root.querySelector('.market-intro-name-copy').textContent=display;this.root.querySelector('.market-feedback').textContent='BLACK-MARKET TERMINAL OFFLINE';this.updateIntegrity()}
  begin(){this.root.dataset.stage='play';this.render();setTimeout(()=>this.root.querySelector('.market-input').focus(),50)}
  render(){const q=TASKS[this.index];if(!q)return;this.value='';this.locked=false;this.root.classList.remove('market-correct','market-wrong','drone-attack','container-open');this.root.querySelector('.market-count').textContent=`CONTAINER ${String(this.index+1).padStart(2,'0')} / 12`;this.root.querySelector('.market-progress i').style.width=`${this.index/12*100}%`;this.root.querySelector('.market-sentence-a').textContent=q.a;this.root.querySelector('.market-sentence-b').textContent=q.b;const input=this.root.querySelector('.market-input');input.value='';input.disabled=false;input.dataset.expected=q.answer;this.root.querySelector('.market-feedback').textContent='LEXA // TYPE WITH YOUR PHYSICAL KEYBOARD. PRESS ENTER TO VERIFY.';this.root.querySelectorAll('.market-hint').forEach(x=>{x.disabled=false;x.classList.remove('used');x.querySelector('b').textContent=x.dataset.marketAction==='verb'?'SHOW VERB':'SHOW PARTICLE'});setTimeout(()=>input.focus(),50)}
  key(k){if(this.locked)return;if(k==='CLEAR')this.value='';else if(k==='BACK')this.value=this.value.slice(0,-1);else if(k==='SPACE'){this.value=this.value.trimEnd();if(this.value&&!this.value.includes(' '))this.value+=' '}else if(/^[A-Z]$/.test(k)&&this.value.length<18)this.value+=k;this.value=this.value.replace(/\s+/g,' ');this.paintInput();const exact=value=>String(value||'').trim().toUpperCase().replace(/\s+/g,' '),expected=this.root.querySelector('.market-input').dataset.expected;if(exact(this.value)===exact(expected))this.verify()}
  paintInput(){const input=this.root.querySelector('.market-input'),clean=this.value.toUpperCase().replace(/[^A-Z ]/g,'').replace(/\s+/g,' ');this.value=clean;input.dataset.value=clean;input.textContent=clean||'TYPE THE ANSWER ONCE'}
  hint(type){if(this.locked)return;const parts=TASKS[this.index].answer.split(' '),word=type==='verb'?parts.slice(0,-1).join(' '):parts.at(-1),button=this.root.querySelector(`[data-market-action="${type}"]`);button.disabled=true;button.classList.add('used');button.querySelector('b').textContent=word;this.root.querySelector('.market-feedback').textContent=`LEXA // ${type==='verb'?'VERB FORM':'PARTICLE'} TRACE DECRYPTED: ${word}`}
  verify(){if(this.locked)return;const input=this.root.querySelector('.market-input'),normalize=value=>String(value||'').normalize('NFKC').toUpperCase().replace(/[^A-Z ]/g,'').trim().replace(/\s+/g,' '),answer=normalize(input.value),expected=normalize(TASKS[this.index].answer);if(!answer){input.focus();return}if(answer===expected){this.value=answer;input.value=answer;input.disabled=true;this.locked=true;this.root.classList.add('market-correct','container-open');this.root.querySelector('.market-feedback').textContent='DOUBLE MEANING VERIFIED // CONTAINER OPEN';this.root.querySelector('.market-progress i').style.width=`${(this.index+1)/12*100}%`;try{this.sfx?.correct?.()}catch{}this.timer=setTimeout(()=>{this.index++;if(this.index===TASKS.length)this.onComplete?.();else this.render()},1450);return}this.integrity--;this.root.classList.add('market-wrong','drone-attack');this.root.querySelector('.market-feedback').textContent=`SEMANTIC MISMATCH // YOU ENTERED: ${answer}`;try{this.sfx?.wrong?.()}catch{}this.updateIntegrity();input.focus();input.select();this.timer=setTimeout(()=>{this.root.classList.remove('market-wrong','drone-attack');if(this.integrity<=0){this.integrity=3;this.updateIntegrity();this.root.querySelector('.market-feedback').textContent='LEXA // Shield rebooted. Re-enter the code and press ENTER.'}},850)}
  updateIntegrity(){this.root.querySelectorAll('.market-shield i').forEach((x,i)=>x.classList.toggle('on',i<this.integrity))}
  exit(){this.clear();this.onExit?.()}
  clear(){clearTimeout(this.timer);this.locked=false;this.root.classList.remove('market-correct','market-wrong','drone-attack','container-open')}
}
