const staircase=[
  {context:'Leo was walking home when he saw a café. He entered because he wanted some coffee.',answer:['LEO','STOPPED','TO HAVE','COFFEE'],blocks:['LEO','STOPPED','HAVING','TO HAVE','COFFEE','SMOKING','HAD']},
  {context:"Leo doesn't smoke anymore.",answer:['LEO','STOPPED','SMOKING'],blocks:['LEO','STOPPED','TO SMOKE','SMOKING','WILL SMOKE']},
  {context:'Mara tested lowering the shield power as a possible solution.',answer:['MARA','TRIED','REDUCING','THE POWER'],blocks:['MARA','TRIED','TO REDUCE','REDUCING','THE POWER','REDUCED']},
  {context:'I met Dr. Vale years ago. I still remember that moment clearly.',answer:['I','REMEMBER','MEETING','DR. VALE'],blocks:['I','REMEMBER','TO MEET','MEETING','DR. VALE','WILL','YESTERDAY']}
];

const bossPhases=[
  {ring:'MEMORY',context:'I can clearly remember the moment when I first saw Lexara-9.',answer:['I','REMEMBER','SEEING','LEXARA-9'],blocks:['I','REMEMBER','TO SEE','SEEING','LEXARA-9','WILL SEE']},
  {ring:'PURPOSE',context:'TOPKRENDEL paused during the escape because he wanted to help an injured robot.',answer:['TOPKRENDEL','STOPPED','TO HELP','THE ROBOT'],blocks:['TOPKRENDEL','STOPPED','HELPING','TO HELP','THE ROBOT','HELPED']},
  {ring:'EXPERIENCE',context:'The engine was overheating. PANGVA experimented with reducing its power.',answer:['PANGVA','TRIED','REDUCING','THE POWER'],blocks:['PANGVA','TRIED','TO REDUCE','REDUCING','THE POWER','REDUCED']},
  {ring:'INTENTION',context:'LEXA is about to announce some terrible news.',answer:['LEXA','REGRETS','TO INFORM','YOU'],blocks:['LEXA','REGRETS','INFORMING','TO INFORM','YOU','INFORMED']}
];

export class InfiniteLoopMission{
  constructor(root,{onComplete,onExit}){this.root=root;this.onComplete=onComplete;this.onExit=onExit;this.work=root.querySelector('#loopWorkarea');this.title=root.querySelector('#loopTitle');this.trial=root.querySelector('#loopTrial');this.context=root.querySelector('#loopContext');this.feedback=root.querySelector('#loopFeedback');this.stage=root.querySelector('.loop-stage-label');this.rings=[...root.querySelectorAll('.loop-rings i')];this.timers=[];document.addEventListener('keydown',e=>{if(e.code!=='KeyE'||!this.root.classList.contains('active'))return;const target=this.root.querySelector('.sentence-block:hover,.rubble-block:hover,[data-mod]:hover,[data-door]:hover')||(document.activeElement?.closest?.('#infiniteLoop')?document.activeElement:null);target?.click()})}
  later(fn,delay){const timer=setTimeout(fn,delay);this.timers.push(timer);return timer}
  clear(){this.timers.forEach(clearTimeout);this.timers=[];clearInterval(this.battleTimer);this.work.innerHTML='';this.root.className='screen'}
  play(){this.clear();this.root.classList.add('active','loop-intro');this.rings.forEach(r=>r.className='');this.trial.textContent='LEXA // WARNING';this.title.textContent='THE INFINITE LOOP';this.context.textContent='Unknown FORM subsystem detected. This sector should not exist.';this.stage.textContent='ENTERING UNKNOWN SECTOR';this.feedback.textContent='THE FORM ENGINE IS REWRITING LOCAL SPACE.';this.work.innerHTML='<div class="loop-entry-core"><i></i><b>FORM CORE</b><span>SUBSYSTEM BREACH</span></div>';this.later(()=>{this.root.classList.add('loop-fall');this.feedback.textContent='FLOOR INTEGRITY LOST // DESCENDING…'},1900);this.later(()=>this.startStaircase(0),3500)}
  scene(name){this.root.className=`screen active loop-${name}`;this.work.innerHTML='';this.feedback.className='loop-feedback'}
  shuffle(items){const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result}
  sentencePuzzle(data,onComplete,onWrong){let selected=[];this.work.innerHTML='<div class="sentence-slots"></div><div class="sentence-blocks"></div>';const slots=this.work.querySelector('.sentence-slots'),bank=this.work.querySelector('.sentence-blocks');slots.innerHTML=data.answer.map((_,i)=>`<button class="sentence-slot" data-slot="${i}">[ ]</button>`).join('');const choose=value=>{const expected=data.answer[selected.length];if(value!==expected){this.feedback.textContent='MEANING MISMATCH DETECTED.';this.feedback.classList.add('error');this.work.classList.add('path-collapse');this.later(()=>{selected=[];slots.querySelectorAll('button').forEach(x=>{x.textContent='[ ]';x.className='sentence-slot'});bank.querySelectorAll('button').forEach(x=>x.disabled=false);this.work.classList.remove('path-collapse');this.feedback.classList.remove('error');this.feedback.textContent='THE LOOP HAS RETURNED YOU TO THE START.';onWrong?.()},950);return}selected.push(value);const slot=slots.children[selected.length-1];slot.textContent=value;slot.classList.add('stable');[...bank.children].find(x=>x.dataset.value===value&&!x.disabled).disabled=true;if(selected.length===data.answer.length){this.feedback.textContent='PATH STABLE';this.feedback.classList.add('success');this.work.classList.add('path-stable');this.later(onComplete,1050)}};this.shuffle(data.blocks).forEach(value=>{const block=document.createElement('button');block.className='sentence-block';block.textContent=value;block.dataset.value=value;block.draggable=true;block.onclick=()=>choose(value);block.ondragstart=e=>e.dataTransfer.setData('text/plain',value);bank.append(block)});slots.ondragover=e=>e.preventDefault();slots.ondrop=e=>{e.preventDefault();choose(e.dataTransfer.getData('text/plain'))}}
  startStaircase(index){this.scene('staircase');const data=staircase[index];this.stage.textContent=`TRIAL 01 // FLIGHT ${index+1} OF ${staircase.length}`;this.trial.textContent='THE BROKEN STAIRCASE // SENTENCE PATH';this.title.textContent='REBUILD THE ASCENT';this.context.textContent=data.context;this.feedback.textContent='E // GRAB A WORD BLOCK OR CLICK IT. BUILD THE MEANING.';this.sentencePuzzle(data,()=>index+1<staircase.length?this.startStaircase(index+1):this.startRubble())}
  startRubble(){this.scene('rubble');this.stage.textContent='TRIAL 02 // CORRUPTION PURGE';this.trial.textContent='THE RUBBLE CHAMBER';this.title.textContent='DESTROY THE CORRUPTED WORDS';this.context.textContent='You are about to give someone bad news.';this.feedback.textContent='LEAVE ONLY: I REGRET TO TELL YOU ABOUT THE FAILURE.';const required=['I','REGRET','TO TELL','YOU','ABOUT','THE FAILURE'],corrupt=['TELLING','TOLD','TO','WILL TELL'];const all=this.shuffle([...required,...corrupt]);this.work.innerHTML='<div class="rubble-grid"></div>';const grid=this.work.firstElementChild;const reset=()=>{grid.innerHTML='';all.forEach(word=>{const block=document.createElement('button');block.className='rubble-block';block.textContent=word;block.onclick=()=>{if(required.includes(word)){this.feedback.textContent='ESSENTIAL BLOCK DESTROYED // RUBBLE RESTORING.';this.work.classList.add('rubble-reset');this.later(()=>{this.work.classList.remove('rubble-reset');reset()},850);return}block.classList.add('destroyed');block.disabled=true;if([...grid.children].filter(x=>corrupt.includes(x.textContent)&&!x.disabled).length===0){this.feedback.textContent='CORRUPTION REMOVED // PASSAGE OPEN';this.feedback.classList.add('success');this.later(()=>this.startDoors(),1100)}};grid.append(block)})};reset()}
  startDoors(){this.scene('doors');this.stage.textContent='TRIAL 03 // SEMANTIC LOOP';this.trial.textContent='THE TWO DOORS';this.title.textContent='CHOOSE THE MEANING';this.context.textContent='Maya wanted to improve her English. Her teacher suggested using podcasts as a new method. TRY…';this.feedback.textContent='ONE DOOR CONTINUES THE EXPERIMENT. THE OTHER RETURNS HERE.';this.work.innerHTML='<div class="loop-doors"><button data-door="to"><small>ATTEMPT A DIFFICULT ACTION</small><b>TRY TO</b></button><button data-door="ing"><small>EXPERIMENT WITH A METHOD</small><b>TRY -ING</b></button></div>';this.work.querySelectorAll('[data-door]').forEach(door=>door.onclick=()=>{if(door.dataset.door==='ing'){door.classList.add('correct');this.feedback.textContent='MEANING VERIFIED // DOOR UNLOCKED';this.later(()=>this.startForge(),1100)}else{door.classList.add('wrong');this.root.classList.add('door-loop');this.feedback.textContent='YOU HAVE BEEN HERE BEFORE.';this.later(()=>this.startDoors(),1250)}})}
  startForge(){this.scene('forge');this.stage.textContent='TRIAL 04 // FORM ENGINE';this.trial.textContent='FORM FORGE';this.title.textContent='CREATE THE FORM';this.context.textContent='She regrets ___ him the truth. The regret concerns a past action.';this.feedback.textContent='COMBINE THE BASE VERB WITH THE CORRECT ENERGY MODIFIER.';this.work.innerHTML='<div class="form-forge"><div class="base-verb">TELL</div><div class="forge-plus">+</div><button data-mod="to">TO</button><button data-mod="ing">-ING</button><div class="forge-output">FORM ENGINE</div></div>';this.work.querySelectorAll('[data-mod]').forEach(button=>button.onclick=()=>{if(button.dataset.mod==='ing'){this.work.querySelector('.forge-output').textContent='TELLING';this.work.classList.add('forge-success');this.feedback.textContent='FORM PERFECT // BOSS CHAMBER UNLOCKED';this.later(()=>this.startBoss(0),1300)}else{this.work.classList.add('forge-error');this.feedback.textContent='MEANING MISMATCH // FORM REJECTED';this.later(()=>this.startForge(),900)}})}
  startBoss(phase){this.scene('boss');this.rings.forEach((ring,i)=>ring.classList.toggle('destroyed',i<phase));this.stage.textContent=`THE LOOPKEEPER // RING ${phase+1} OF 4`;this.trial.textContent=`BOSS PHASE ${phase+1} // ${bossPhases[phase].ring}`;this.title.textContent='BUILD THE BRIDGE';this.context.textContent=bossPhases[phase].context;this.feedback.textContent='A WRONG BRIDGE RESTORES THE PREVIOUS RING.';this.sentencePuzzle(bossPhases[phase],()=>{this.rings[phase].classList.add('destroyed');this.feedback.textContent=`${bossPhases[phase].ring} RING DESTROYED`;this.later(()=>phase===3?this.startBattle():this.startBoss(phase+1),1100)},()=>{if(phase>0){this.rings[phase-1].classList.remove('destroyed');this.later(()=>this.startBoss(phase-1),250)}})}
  startBattle(){this.scene('battle');this.rings.forEach(r=>r.classList.add('destroyed'));this.stage.textContent='FINAL PHASE // 8.0 SECONDS';this.trial.textContent='LOOP BROKEN';this.title.textContent='THE LOOPKEEPER IS VULNERABLE';this.context.textContent='Fire repeatedly into the exposed FORM energy core.';this.feedback.textContent='DESTROY THE CORE BEFORE THE LOOP RESTARTS.';let hits=0,time=8;this.work.innerHTML='<button class="loopkeeper-core"><i></i><b>FORM CORE</b><span>0 / 10</span></button><div class="battle-clock">8.0</div>';const core=this.work.querySelector('.loopkeeper-core'),clock=this.work.querySelector('.battle-clock');core.onclick=()=>{hits++;core.querySelector('span').textContent=`${hits} / 10`;core.classList.remove('hit');void core.offsetWidth;core.classList.add('hit');if(hits>=10){clearInterval(this.battleTimer);this.feedback.textContent='FORM PERFECT // THE LOOP HAS ENDED';this.root.classList.add('loopkeeper-defeated');this.later(()=>this.onComplete?.(),1500)}};this.battleTimer=setInterval(()=>{time-=.1;clock.textContent=Math.max(0,time).toFixed(1);if(time<=0){clearInterval(this.battleTimer);this.feedback.textContent='LOOP RESET // ONE FINAL FORM PUZZLE REQUIRED';this.later(()=>this.startBoss(3),900)}},100)}
  exit(){this.clear();this.onExit?.()}
}
