const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const smooth=v=>{v=clamp(v);return v*v*(3-2*v)};
const mix=(a,b,t)=>a+(b-a)*smooth(t);

export class FinalThroneCutscene{
  constructor(canvas,ui={}){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.ui=ui;this.active=false;this.duration=13;this.resize=this.resize.bind(this);this.loop=this.loop.bind(this)}
  async play(hero='KAEL'){this.dispose();this.hero=hero;this.female=hero==='NYRA'||hero==='PANGVA';this.time=0;this.last=performance.now();this.fired=new Set();this.particles=Array.from({length:150},()=>({x:Math.random(),y:Math.random(),s:.5+Math.random()*2,v:.006+Math.random()*.018,c:['#ff8a22','#ff35b8','#46ecff'][Math.floor(Math.random()*3)]}));this.ui.root?.classList.remove('cutscene-final');this.ui.title?.classList.remove('visible');this.ui.returnButton?.classList.remove('visible');this.ui.skipButton.hidden=false;this.resize();addEventListener('resize',this.resize);await this.loadAssets();if(!this.canvas.isConnected)return;this.active=true;this.last=performance.now();this.loop(this.last)}
  image(file){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=`assets/images/${file}`})}
  async loadAssets(){const prefix=this.female?'pangva':'topkrendel';const [seated,crowned,crown]=await Promise.all([this.image(`${prefix}-throne-uncrowned.png`),this.image(`${prefix}-throne-crowned.png`),this.image('lexa-crown-source.png')]);this.assets={seated,crowned,crown:this.chroma(crown)}}
  chroma(img){const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0);const p=x.getImageData(0,0,c.width,c.height),d=p.data;for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2],key=g-Math.max(r,b);if(g>85&&key>22){d[i+3]=Math.max(0,255-(key-22)*6.4);d[i+1]=Math.min(g,Math.max(r,b)+7)}}x.putImageData(p,0,0);return c}
  resize(){const d=Math.min(devicePixelRatio||1,1.5);this.w=innerWidth;this.h=innerHeight;this.canvas.width=Math.round(this.w*d);this.canvas.height=Math.round(this.h*d);this.canvas.style.width=this.w+'px';this.canvas.style.height=this.h+'px';this.ctx.setTransform(d,0,0,d,0,0)}
  cover(img,zoom=1,cx=.5,cy=.5,alpha=1){const s=Math.max(this.w/img.width,this.h/img.height)*zoom,sw=this.w/s,sh=this.h/s,sx=clamp(img.width*cx-sw/2,0,Math.max(0,img.width-sw)),sy=clamp(img.height*cy-sh/2,0,Math.max(0,img.height-sh));this.ctx.globalAlpha=alpha;this.ctx.drawImage(img,sx,sy,sw,sh,0,0,this.w,this.h);this.ctx.globalAlpha=1}
  drawSeated(t){const final=t>=7,img=final?this.assets.crowned:this.assets.seated,zoom=t<7?mix(1.04,1.12,t/7):mix(1.12,1.02,(t-7)/6);this.cover(img,zoom,.5,.49,1)}
  drawCrown(t){if(t<3||t>=7)return;const p=smooth((t-3)/4),img=this.assets.crown;const crownedX=.5,crownedY=this.female?.205:.25,width=this.w*(this.female?.082:.073),height=width*img.height/img.width,x=crownedX*this.w-width/2,y=mix(-height*1.2,crownedY*this.h,p);this.ctx.save();this.ctx.shadowColor='#fff5a0';this.ctx.shadowBlur=22+22*p;this.ctx.drawImage(img,x,y,width,height);this.ctx.restore();for(let i=0;i<18;i++){const a=i/18*Math.PI*2,r=(1-p)*this.w*.18;this.ctx.fillStyle=['#ff8a22','#ff35b8','#46ecff'][i%3];this.ctx.globalAlpha=.8*(1-p);this.ctx.beginPath();this.ctx.arc(this.w*.5+Math.cos(a)*r,this.h*(crownedY+.05)+Math.sin(a)*r*.35,2+i%3,0,Math.PI*2);this.ctx.fill()}this.ctx.globalAlpha=1}
  drawEnergy(t){if(t<2)return;const power=clamp((t-2)/5);this.ctx.save();this.ctx.globalCompositeOperation='screen';for(let i=0;i<3;i++){const color=['#ff861f','#ff35b8','#35ecff'][i],a=t*.8+i*Math.PI*2/3,x=this.w*.5+Math.cos(a)*this.w*.18,y=this.h*.25+Math.sin(a)*this.h*.055;this.ctx.strokeStyle=color;this.ctx.shadowColor=color;this.ctx.shadowBlur=20;this.ctx.lineWidth=3;this.ctx.beginPath();this.ctx.arc(x,y,9+5*Math.sin(t*2+i),0,Math.PI*2);this.ctx.stroke();if(t<7){this.ctx.globalAlpha=.65*power;this.ctx.beginPath();this.ctx.moveTo(x,y);this.ctx.lineTo(this.w*.5,this.h*.25);this.ctx.stroke();this.ctx.globalAlpha=1}}
    if(t>=7){const p=clamp((t-7)/1.4);this.ctx.strokeStyle='#fff';this.ctx.lineWidth=8*(1-p);this.ctx.globalAlpha=1-p;this.ctx.beginPath();this.ctx.arc(this.w*.5,this.h*.48,p*this.w*.62,0,Math.PI*2);this.ctx.stroke();this.ctx.globalAlpha=1}this.ctx.restore()}
  drawParticles(dt,t){this.ctx.save();this.ctx.globalCompositeOperation='screen';for(const p of this.particles){p.y-=p.v*dt*(t>7?5:1);if(p.y<-.02){p.y=1.02;p.x=Math.random()}this.ctx.fillStyle=p.c;this.ctx.globalAlpha=.22+(t>7?.5:0);this.ctx.fillRect(p.x*this.w,p.y*this.h,p.s,p.s*2.4)}this.ctx.restore();this.ctx.globalAlpha=1}
  sound(label){if(this.fired.has(label))return;this.fired.add(label);try{this.audio??=new AudioContext();const map={doors:[48,.8,.07],walk:[92,.07,.018],sit:[170,.3,.035],crown:[420,2,.035],final:[720,1.5,.075]},v=map[label.startsWith('walk')?'walk':label],n=this.audio.currentTime,o=this.audio.createOscillator(),g=this.audio.createGain();o.type=label==='final'?'triangle':'sawtooth';o.frequency.setValueAtTime(v[0],n);if(label==='crown')o.frequency.exponentialRampToValueAtTime(1100,n+v[1]);g.gain.setValueAtTime(v[2],n);g.gain.exponentialRampToValueAtTime(.001,n+v[1]);o.connect(g).connect(this.audio.destination);o.start();o.stop(n+v[1])}catch{}}
  updateSound(t){if(t>.05)this.sound('sit');if(t>3)this.sound('crown');if(t>7)this.sound('final')}
  render(dt){const t=this.time;this.ctx.clearRect(0,0,this.w,this.h);this.drawSeated(t);this.drawCrown(t);this.drawEnergy(t);this.drawParticles(dt,t);if(t>=9)this.showFinal()}
  loop(now){if(!this.active)return;this.raf=requestAnimationFrame(this.loop);const dt=Math.min((now-this.last)/1000,.05);this.last=now;this.time=Math.min(this.duration,this.time+dt);this.render(dt);this.updateSound(this.time)}
  showFinal(){this.ui.root?.classList.add('cutscene-final');this.ui.title?.classList.add('visible');this.ui.returnButton?.classList.add('visible');this.ui.skipButton.hidden=true}
  skip(){if(!this.active)return;this.time=9.2;this.render(.016);this.showFinal()}
  dispose(){this.active=false;cancelAnimationFrame(this.raf);removeEventListener('resize',this.resize);this.audio?.close?.();this.audio=null}
}
